import React, { createContext, useContext, useState } from 'react';

export type Lang = 'en' | 'sw';

// ---------------------------------------------------------------------------
// Translation dictionaries
// ---------------------------------------------------------------------------

const en = {
  // App
  appName: 'AP LIS',
  appFull: 'Anatomic Pathology Laboratory Information System',

  // Nav
  nav_home: 'Home',
  nav_orderEntry: 'Order Entry',
  nav_processing: 'Processing',
  nav_result: 'Result',
  nav_query: 'Query',
  nav_logout: 'Logout',

  // Common
  save: 'Save',
  delete: 'Delete',
  search: 'Search',
  cancel: 'Cancel',
  confirm: 'Confirm',
  close: 'Close',
  loading: 'Loading...',
  cases: 'cases',
  results: 'results',
  noResults: 'No matching cases found',
  errorGeneric: 'Something went wrong. Please try again.',

  // Login
  login_findEmployee: 'Find employee',
  login_newEmployee: 'New employee',
  login_searchPlaceholder: 'Search by name or username',
  login_noEmployeesFound: 'No employees found. Try creating a new one.',
  login_firstName: 'First Name',
  login_lastName: 'Last Name',
  login_username: 'Username',
  login_role: 'Role',
  login_createAndLogin: 'Create & Login',
  login_allFieldsRequired: 'All fields are required for a new employee',
  login_failed: 'Login failed. Please try again.',

  // Dashboard
  dash_workflow: 'Workflow',
  dash_orderEntry_title: 'Order Entry',
  dash_orderEntry_desc: 'Register a new pathology case. Enter patient and clinician details, add specimens, and generate the case worksheet.',
  dash_processing_title: 'Processing Queue',
  dash_processing_desc: 'Cases awaiting grossing and block/slide preparation. Select a case to record blocks and slides for each specimen.',
  dash_result_title: 'Result Queue',
  dash_result_desc: 'Cases with slides prepared, ready for microscopic examination and reporting. Sign out completed cases here.',
  dash_query_title: 'Query',
  dash_query_desc: 'Search for any case by case ID or patient ID to review its current status, materials, and reports.',
  dash_systemDesc: 'A lightweight workflow management system for anatomic pathology laboratories. Track cases from initial registration through grossing, slide preparation, microscopic examination, and final sign-out.',
  dash_loggedInAs: 'Logged in as',

  // Processing Queue
  pq_title: 'Processing Queue',
  pq_searchPlaceholder: 'Search case ID, patient ID or patient name',
  pq_showAll: 'Show all (including completed)',
  pq_caseId: 'Case ID',
  pq_patient: 'Patient',
  pq_clinician: 'Clinician',
  pq_registered: 'Registered',
  pq_type: 'Type',
  pq_specimens: 'Specimens',
  pq_noCases: 'No cases in queue',

  // Result Queue
  rq_title: 'Result Queue',
  rq_pendingResult: 'Pending Result',
  rq_reactivated: 'Reactivated',
  rq_status: 'Status',
  rq_noCases: 'No cases pending result',

  // Query
  q_title: 'Query',
  q_caseId: 'Case ID',
  q_patientId: 'Patient ID',
  q_search: 'Search',
  q_status: 'Status',
  q_signedOut: 'Signed Out',
  q_inProgress: 'In Progress',
  q_noResults: 'No matching cases found',
  q_error: 'Search failed. Please try again.',
  q_searchFailed: 'Search failed. Please try again.',

  // Order Entry
  oe_title: 'Order Entry',
  oe_patient: 'Patient',
  oe_existing: 'Existing',
  oe_new: 'New',
  oe_searchPatient: 'Search patient',
  oe_searchClinician: 'Search clinician',
  oe_clinician: 'Clinician',
  oe_caseDetails: 'Case Details',
  oe_caseType: 'Case Type',
  oe_surgicalPathology: 'Surgical Pathology',
  oe_cytology: 'Cytology',
  oe_specimens: 'Specimens',
  oe_addSpecimen: 'Add Specimen',
  oe_specimen: 'Specimen',
  oe_site: 'Site',
  oe_organ: 'Organ',
  oe_specimenType: 'Specimen Type',
  oe_coldIschemicTime: 'Cold Ischemic Time (min)',
  oe_createCase: 'Create Case',
  oe_caseCreated: 'Case created:',
  oe_worksheetPdf: 'Worksheet PDF',
  oe_sex: 'Sex',
  oe_dob: 'Date of Birth',
  oe_firstName: 'First Name',
  oe_lastName: 'Last Name',
  oe_dateOfBirth: 'Date of Birth',
  oe_sexMale: 'Male',
  oe_sexFemale: 'Female',
  oe_sexOther: 'Other',
  oe_sexUnknown: 'Unknown',

  // Processing Case
  pc_referenceStrips: 'Reference Strips PDF',
  pc_referenceStripsPdf: 'Reference Strips PDF',
  pc_save: 'Save',
  pc_saved: 'Case saved',
  pc_caseSaved: 'Case saved',
  pc_saveFailed: 'Failed to save case',
  pc_clinicalHistory: 'Clinical History',
  pc_grossDescription: 'Gross Description',
  pc_materials: 'Materials',
  pc_noSpecimens: 'No specimens found for this case.',
  pc_blockId: 'Block ID',
  pc_slides: 'Slides',
  pc_addSlides: 'Add Slides',
  pc_addSlidesHeader: 'Add Slides',
  pc_deleteBlock: 'Delete block and all its slides',
  pc_deleteBlockTooltip: 'Delete block and all its slides',
  common_delete: 'Delete',
  pc_numBlocks: '# Blocks',
  pc_numSlides: '# Slides',
  pc_addBlock: 'Add Block',
  pc_addBlocks: 'Add Blocks',
  pc_addSlide: 'Add Slide',
  pc_addSlidesBtn: 'Add Slides',
  pc_noSlides: 'none',
  pc_none: 'none',
  pc_noSlidesYet: 'No slides yet',
  pc_slideType: 'Type',

  // Result Case
  rc_processing: 'Processing',
  rc_finalDiagnosis: 'Final Diagnosis',
  rc_comment: 'Comment',
  rc_microscopicDescription: 'Microscopic Description',
  rc_grossDescription: 'Gross Description',
  rc_clinicalHistory: 'Clinical History',
  rc_capTemplate: 'CAP Template (optional)',
  rc_microscopicContent: 'Microscopic Description',
  rc_saveDraft: 'Save Draft',
  rc_signOut: 'Sign Out',
  rc_reactivate: 'Reactivate',
  rc_signedOut: 'Signed Out',
  rc_draftSaved: 'Draft saved',
  rc_historySaved: 'Clinical history saved',
  rc_clinicalHistorySaved: 'Clinical history saved',
  rc_report: 'Report',
  rc_history: 'History',
  rc_materials: 'Materials',
  rc_reportPdf: 'Report PDF',
  rc_amendedPdf: 'Amended PDF',
  rc_confirmSignOut: 'Confirm Sign-Out',
  rc_confirmSignOutMsg: 'This action is final. The report will become immutable once signed out.',
  rc_confirmReactivate: 'Confirm Reactivation',
  rc_confirmReactivateMsg: 'This will reactivate the case for amendment. Are you sure?',
  rc_version: 'Version',
  rc_pathologist: 'Pathologist',
  rc_date: 'Date',
  rc_signedOutStatus: 'Signed Out',
  rc_inProgress: 'In Progress',
  rc_saveHistory: 'Save History',
  rc_signedOutAlert: 'This case is signed out. Use Reactivate to create a revision or addendum.',
  rc_viewReportPdf: 'View Report PDF',
  rc_capTemplatePlaceholder: 'Select a CAP template above, then fill in the fields',
  rc_dob: 'DOB',
  rc_sex: 'Sex',
  rc_resultEntry: 'Result Entry',
  rc_reportHistory: 'Report History',
  rc_reactivateCase: 'Reactivate Case',
  rc_reactivateMsg: 'Reactivating will create a new draft report. Prior reports remain immutable.',
  rc_revise: 'Revise',
  rc_addend: 'Addend',
  rc_none: 'None',
  rc_final: 'Final',
  rc_draft: 'Draft',
  rc_signedOutSuccess: 'Report signed out successfully',
  rc_reactivatedSuccess: 'Case reactivated. A new draft has been created.',

  // Body sites (surgical)
  site_gi: 'Gastrointestinal (GI)',
  site_hepatobiliary: 'Hepatobiliary & Pancreas',
  site_breast: 'Breast',
  site_gynecologic: 'Gynecologic',
  site_urologic: 'Urologic (GU)',
  site_headNeck: 'Head & Neck',
  site_respiratory: 'Respiratory (Lung & Pleura)',
  site_skin: 'Skin',
  site_lymph: 'Lymph Node / Hematolymphoid',
  site_boneSoft: 'Bone & Soft Tissue',
  site_cns: 'Central Nervous System (CNS)',
  site_placenta: 'Placenta / Products of Conception',

  // Cytology sites
  site_gynCyto: 'GYN Cytology (Pap smears)',
  site_fna: 'Fine Needle Aspiration (FNA)',
  site_fluidCyto: 'Fluid Cytology (Effusions)',
  site_urine: 'Urine Cytology',
  site_respCyto: 'Respiratory Cytology',
  site_csf: 'CSF (Cerebrospinal fluid)',
  site_bodyFluid: 'Body Fluid (Non-effusion)',

  // Organs (surgical)
  organ_esophagus: 'Esophagus',
  organ_stomach: 'Stomach',
  organ_duodenum: 'Duodenum',
  organ_smallBowel: 'Small bowel (jejunum/ileum)',
  organ_colon: 'Colon',
  organ_rectum: 'Rectum',
  organ_appendix: 'Appendix',
  organ_anus: 'Anus',
  organ_liver: 'Liver',
  organ_gallbladder: 'Gallbladder',
  organ_bileDuct: 'Bile duct',
  organ_pancreas: 'Pancreas',
  organ_breast: 'Breast',
  organ_axillary: 'Axillary tissue',
  organ_cervix: 'Cervix',
  organ_endometrium: 'Endometrium',
  organ_myometrium: 'Myometrium',
  organ_ovary: 'Ovary',
  organ_fallopian: 'Fallopian tube',
  organ_vulva: 'Vulva',
  organ_vagina: 'Vagina',
  organ_prostate: 'Prostate',
  organ_bladder: 'Bladder',
  organ_kidney: 'Kidney',
  organ_ureter: 'Ureter',
  organ_testis: 'Testis',
  organ_epididymis: 'Epididymis',
  organ_penis: 'Penis',
  organ_oralCavity: 'Oral cavity',
  organ_tongue: 'Tongue',
  organ_salivaryGland: 'Salivary gland',
  organ_thyroid: 'Thyroid',
  organ_parathyroid: 'Parathyroid',
  organ_larynx: 'Larynx',
  organ_pharynx: 'Pharynx',
  organ_nasalSinus: 'Nasal cavity / Sinus',
  organ_neckSoftTissue: 'Neck (soft tissue/unspecified)',
  organ_lung: 'Lung',
  organ_pleura: 'Pleura',
  organ_bronchus: 'Bronchus',
  organ_skin: 'Skin',
  organ_lymphNode: 'Lymph node',
  organ_spleen: 'Spleen',
  organ_bonemarrow: 'Bone marrow',
  organ_bone: 'Bone',
  organ_softTissue: 'Soft tissue',
  organ_brain: 'Brain',
  organ_spinalCord: 'Spinal cord',
  organ_meninges: 'Meninges',
  organ_placenta: 'Placenta',
  organ_poc: 'Products of conception',

  // Cytology organs / sub-sites
  organ_pleuralFluid: 'Pleural fluid',
  organ_asciticFluid: 'Ascitic fluid',
  organ_pericardialFluid: 'Pericardial fluid',
  organ_sputum: 'Sputum',
  organ_bronchialWash: 'Bronchial wash',
  organ_bronchialBrush: 'Bronchial brush',
  organ_bal: 'BAL (bronchoalveolar lavage)',
  organ_synovialFluid: 'Synovial fluid',
  organ_cystFluid: 'Cyst fluid',
  organ_other: 'Other',
  organ_gynCytoSite: 'GYN Cytology (Pap smears)',
  organ_urineCytoSite: 'Urine Cytology',
  organ_csfSite: 'CSF (Cerebrospinal fluid)',
} as const;

const sw: Record<keyof typeof en, string> = {
  appName: 'AP LIS',
  appFull: 'Mfumo wa Habari wa Maabara ya Patholojia',

  nav_home: 'Nyumbani',
  nav_orderEntry: 'Kuingiza Oda',
  nav_processing: 'Kusindika',
  nav_result: 'Matokeo',
  nav_query: 'Utafutaji',
  nav_logout: 'Toka',

  save: 'Hifadhi',
  delete: 'Futa',
  search: 'Tafuta',
  cancel: 'Ghairi',
  confirm: 'Thibitisha',
  close: 'Funga',
  loading: 'Inapakia...',
  cases: 'kesi',
  results: 'matokeo',
  noResults: 'Hakuna kesi zinazolingana',
  errorGeneric: 'Hitilafu imetokea. Tafadhali jaribu tena.',

  login_findEmployee: 'Tafuta mfanyakazi',
  login_newEmployee: 'Mfanyakazi mpya',
  login_searchPlaceholder: 'Tafuta kwa jina au jina la mtumiaji',
  login_noEmployeesFound: 'Hakuna mfanyakazi aliyepatikana. Jaribu kuunda mpya.',
  login_firstName: 'Jina la Kwanza',
  login_lastName: 'Jina la Familia',
  login_username: 'Jina la Mtumiaji',
  login_role: 'Jukumu',
  login_createAndLogin: 'Unda & Ingia',
  login_allFieldsRequired: 'Sehemu zote zinahitajika kwa mfanyakazi mpya',
  login_failed: 'Kuingia kumeshindwa. Tafadhali jaribu tena.',

  dash_workflow: 'Mtiririko wa Kazi',
  dash_orderEntry_title: 'Kuingiza Oda',
  dash_orderEntry_desc: 'Sajili kesi mpya ya patholojia. Weka taarifa za mgonjwa na daktari, ongeza sampuli, na uzalishe karatasi ya kazi.',
  dash_processing_title: 'Foleni ya Kusindika',
  dash_processing_desc: 'Kesi zinazosubiri kuchunguzwa kwa macho na kuandaa blocks/slides. Chagua kesi ili kurekodi blocks na slides kwa kila sampuli.',
  dash_result_title: 'Foleni ya Matokeo',
  dash_result_desc: 'Kesi zenye slides zikiwa tayari kwa uchunguzi wa darubini na kuandika ripoti. Sahihi kesi zilizokamilika hapa.',
  dash_query_title: 'Utafutaji',
  dash_query_desc: 'Tafuta kesi yoyote kwa nambari ya kesi au nambari ya mgonjwa ili kukagua hali yake ya sasa, vifaa, na ripoti.',
  dash_systemDesc: 'Mfumo mwepesi wa usimamizi wa mtiririko wa kazi kwa maabara za patholojia ya anatomiki. Fuatilia kesi kuanzia usajili kupitia kuchunguza kwa macho ya nje, kuandaa slides, uchunguzi wa darubini, na kutoa sahihi ya mwisho.',
  dash_loggedInAs: 'Umeingia kama',

  pq_title: 'Foleni ya Kusindika',
  pq_searchPlaceholder: 'Tafuta nambari ya kesi, kitambulisho au jina la mgonjwa',
  pq_showAll: 'Onyesha zote (pamoja na zilizokamilika)',
  pq_caseId: 'Nambari ya Kesi',
  pq_patient: 'Mgonjwa',
  pq_clinician: 'Daktari',
  pq_registered: 'Ilisajiliwa',
  pq_type: 'Aina',
  pq_specimens: 'Sampuli',
  pq_noCases: 'Hakuna kesi kwenye foleni',

  rq_title: 'Foleni ya Matokeo',
  rq_pendingResult: 'Inasubiri Matokeo',
  rq_reactivated: 'Imeanzishwa Upya',
  rq_status: 'Hali',
  rq_noCases: 'Hakuna kesi zinazosubiri matokeo',

  q_title: 'Utafutaji',
  q_caseId: 'Nambari ya Kesi',
  q_patientId: 'Nambari ya Mgonjwa',
  q_search: 'Tafuta',
  q_status: 'Hali',
  q_signedOut: 'Imetolewa Sahihi',
  q_inProgress: 'Inaendelea',
  q_noResults: 'Hakuna kesi zinazolingana',
  q_error: 'Utafutaji umeshindwa. Tafadhali jaribu tena.',
  q_searchFailed: 'Utafutaji umeshindwa. Tafadhali jaribu tena.',

  oe_title: 'Kuingiza Oda',
  oe_patient: 'Mgonjwa',
  oe_existing: 'Aliyepo',
  oe_new: 'Mpya',
  oe_searchPatient: 'Tafuta mgonjwa',
  oe_searchClinician: 'Tafuta daktari',
  oe_clinician: 'Daktari',
  oe_caseDetails: 'Maelezo ya Kesi',
  oe_caseType: 'Aina ya Kesi',
  oe_surgicalPathology: 'Upasuaji',
  oe_cytology: 'Sitolojia',
  oe_specimens: 'Sampuli',
  oe_addSpecimen: 'Ongeza Sampuli',
  oe_specimen: 'Sampuli',
  oe_site: 'Sehemu ya Mwili',
  oe_organ: 'Kiungo',
  oe_specimenType: 'Aina ya Sampuli',
  oe_coldIschemicTime: 'Muda wa Cold Ischemic (dak)',
  oe_createCase: 'Unda Kesi',
  oe_caseCreated: 'Kesi imeundwa:',
  oe_worksheetPdf: 'PDF ya Karatasi ya Kazi',
  oe_sex: 'Jinsia',
  oe_dob: 'Tarehe ya Kuzaliwa',
  oe_firstName: 'Jina la Kwanza',
  oe_lastName: 'Jina la Familia',
  oe_dateOfBirth: 'Tarehe ya Kuzaliwa',
  oe_sexMale: 'Mwanaume',
  oe_sexFemale: 'Mwanamke',
  oe_sexOther: 'Nyingine',
  oe_sexUnknown: 'Haijulikani',

  pc_referenceStrips: 'PDF ya Kumbukumbu',
  pc_referenceStripsPdf: 'PDF ya Kumbukumbu',
  pc_save: 'Hifadhi',
  pc_saved: 'Kesi imehifadhiwa',
  pc_caseSaved: 'Kesi imehifadhiwa',
  pc_saveFailed: 'Imeshindwa kuhifadhi kesi',
  pc_clinicalHistory: 'Historia ya Mgonjwa',
  pc_grossDescription: 'Maelezo ya Gross',
  pc_materials: 'Vifaa',
  pc_noSpecimens: 'Hakuna sampuli zilizopatikana kwa kesi hii.',
  pc_blockId: 'Nambari ya Block',
  pc_slides: 'Slides',
  pc_addSlides: 'Ongeza Slides',
  pc_addSlidesHeader: 'Ongeza Slides',
  pc_deleteBlock: 'Futa block na slides zake zote',
  pc_deleteBlockTooltip: 'Futa block na slides zake zote',
  common_delete: 'Futa',
  pc_numBlocks: 'Idadi ya Blocks',
  pc_numSlides: 'Idadi ya Slides',
  pc_addBlock: 'Ongeza Block',
  pc_addBlocks: 'Ongeza Blocks',
  pc_addSlide: 'Ongeza Slide',
  pc_addSlidesBtn: 'Ongeza Slides',
  pc_noSlides: 'hakuna',
  pc_none: 'hakuna',
  pc_noSlidesYet: 'Bado hakuna slides',
  pc_slideType: 'Aina',

  rc_processing: 'Kusindika',
  rc_finalDiagnosis: 'Utambuzi wa Mwisho',
  rc_comment: 'Maoni',
  rc_microscopicDescription: 'Maelezo ya Microscopy',
  rc_grossDescription: 'Maelezo ya Gross',
  rc_clinicalHistory: 'Historia ya Mgonjwa',
  rc_capTemplate: 'Kiolezo cha CAP (hiari)',
  rc_microscopicContent: 'Maelezo ya Microscopy',
  rc_saveDraft: 'Hifadhi Rasimu',
  rc_signOut: 'Toa Sahihi',
  rc_reactivate: 'Anzisha Upya',
  rc_signedOut: 'Imetolewa Sahihi',
  rc_draftSaved: 'Rasimu imehifadhiwa',
  rc_historySaved: 'Historia ya mgonjwa imehifadhiwa',
  rc_clinicalHistorySaved: 'Historia ya mgonjwa imehifadhiwa',
  rc_report: 'Ripoti',
  rc_history: 'Historia',
  rc_materials: 'Vifaa',
  rc_reportPdf: 'PDF ya Ripoti',
  rc_amendedPdf: 'PDF Iliyorekebishwa',
  rc_confirmSignOut: 'Thibitisha Kutoa Sahihi',
  rc_confirmSignOutMsg: 'Hatua hii ni ya mwisho. Ripoti itakuwa haiwezi kubadilishwa baada ya kutolewa sahihi.',
  rc_confirmReactivate: 'Thibitisha Kuanzisha Upya',
  rc_confirmReactivateMsg: 'Hii itaanzisha upya kesi kwa urekebishaji. Je, una uhakika?',
  rc_version: 'Toleo',
  rc_pathologist: 'Daktari wa Patholojia',
  rc_date: 'Tarehe',
  rc_signedOutStatus: 'Imetolewa Sahihi',
  rc_inProgress: 'Inaendelea',
  rc_saveHistory: 'Hifadhi Historia',
  rc_signedOutAlert: 'Kesi hii imetolewa sahihi. Tumia Anzisha Upya kuunda toleo jipya au kiongezeko.',
  rc_viewReportPdf: 'Tazama PDF ya Ripoti',
  rc_capTemplatePlaceholder: 'Chagua kiolezo cha CAP hapo juu, kisha jaza sehemu',
  rc_dob: 'Tarehe ya Kuzaliwa',
  rc_sex: 'Jinsia',
  rc_resultEntry: 'Kuingiza Matokeo',
  rc_reportHistory: 'Historia ya Ripoti',
  rc_reactivateCase: 'Anzisha Upya Kesi',
  rc_reactivateMsg: 'Kuanzisha upya kutaunda rasimu mpya ya ripoti. Ripoti za awali hazibadiliki.',
  rc_revise: 'Rekebisha',
  rc_addend: 'Ongeza',
  rc_none: 'Hakuna',
  rc_final: 'ya Mwisho',
  rc_draft: 'Rasimu',
  rc_signedOutSuccess: 'Ripoti imetolewa sahihi',
  rc_reactivatedSuccess: 'Kesi imeanzishwa upya. Rasimu mpya imeundwa.',

  // Body sites
  site_gi: 'Mfumo wa Mmeng\'enyo wa Chakula (GI)',
  site_hepatobiliary: 'Ini, Njia ya Nyongo & Kongosho',
  site_breast: 'Matiti',
  site_gynecologic: 'Mfumo wa Uzazi wa Mwanamke',
  site_urologic: 'Mfumo wa Mkojo na Uzazi wa Mwanaume (GU)',
  site_headNeck: 'Kichwa na Shingo',
  site_respiratory: 'Mfumo wa Upumuaji (Mapafu na Pleura)',
  site_skin: 'Ngozi',
  site_lymph: 'Tezi za Limfu / Mfumo wa Damu na Limfu',
  site_boneSoft: 'Mfupa na Tishu Laini',
  site_cns: 'Mfumo wa Neva wa Kati (CNS)',
  site_placenta: 'Kondo la Nyuma / Mabaki ya Ujauzito',

  site_gynCyto: 'Sitolojia ya GYN (Pap smear)',
  site_fna: 'Fine Needle Aspiration (FNA)',
  site_fluidCyto: 'Sitolojia ya Majimaji (Effusions)',
  site_urine: 'Sitolojia ya Mkojo',
  site_respCyto: 'Sitolojia ya Mfumo wa Upumuaji',
  site_csf: 'Majimaji ya uti wa mgongo (CSF)',
  site_bodyFluid: 'Majimaji ya Mwili (yasiyo effusion)',

  // Organs
  organ_esophagus: 'Umio (Esophagus)',
  organ_stomach: 'Tumbo (Stomach)',
  organ_duodenum: 'Duodenum',
  organ_smallBowel: 'Utumbo mdogo (jejunum/ileum)',
  organ_colon: 'Utumbo mpana (Colon)',
  organ_rectum: 'Rektamu',
  organ_appendix: 'Appendix',
  organ_anus: 'Mkundu (Anus)',
  organ_liver: 'Ini',
  organ_gallbladder: 'Kibofu cha nyongo',
  organ_bileDuct: 'Njia ya nyongo',
  organ_pancreas: 'Kongosho',
  organ_breast: 'Titi',
  organ_axillary: 'Tishu za kwapa',
  organ_cervix: 'Shingo ya kizazi (Cervix)',
  organ_endometrium: 'Uterasi (Endometrium)',
  organ_myometrium: 'Misuli ya uterasi (Myometrium)',
  organ_ovary: 'Ovari',
  organ_fallopian: 'Mirija ya fallopian',
  organ_vulva: 'Vulva',
  organ_vagina: 'Uke (Vagina)',
  organ_prostate: 'Prostate',
  organ_bladder: 'Kibofu cha mkojo',
  organ_kidney: 'Figo',
  organ_ureter: 'Ureta',
  organ_testis: 'Korodani (Testis)',
  organ_epididymis: 'Epididymis',
  organ_penis: 'Uume',
  organ_oralCavity: 'Mdomo (Oral cavity)',
  organ_tongue: 'Ulimi',
  organ_salivaryGland: 'Tezi za mate',
  organ_thyroid: 'Tezi ya thyroid',
  organ_parathyroid: 'Tezi ya parathyroid',
  organ_larynx: 'Larynx',
  organ_pharynx: 'Pharynx',
  organ_nasalSinus: 'Pua / Sinasi',
  organ_neckSoftTissue: 'Shingo (tishu laini/isiyobainishwa)',
  organ_lung: 'Pafu',
  organ_pleura: 'Pleura',
  organ_bronchus: 'Bronchus',
  organ_skin: 'Ngozi',
  organ_lymphNode: 'Tezi ya limfu',
  organ_spleen: 'Wengu (Spleen)',
  organ_bonemarrow: 'Uboho wa mfupa',
  organ_bone: 'Mfupa',
  organ_softTissue: 'Tishu laini',
  organ_brain: 'Ubongo',
  organ_spinalCord: 'Uti wa mgongo',
  organ_meninges: 'Utando wa ubongo (Meninges)',
  organ_placenta: 'Kondo la nyuma',
  organ_poc: 'Mabaki ya ujauzito',

  organ_pleuralFluid: 'Majimaji ya pleura',
  organ_asciticFluid: 'Majimaji ya tumbo (ascitic fluid)',
  organ_pericardialFluid: 'Majimaji ya moyo (pericardial fluid)',
  organ_sputum: 'Makamasi (Sputum)',
  organ_bronchialWash: 'Bronchial wash',
  organ_bronchialBrush: 'Bronchial brush',
  organ_bal: 'BAL (bronchoalveolar lavage)',
  organ_synovialFluid: 'Majimaji ya viungo (Synovial fluid)',
  organ_cystFluid: 'Majimaji ya uvimbe (Cyst fluid)',
  organ_other: 'Nyingine',
  organ_gynCytoSite: 'Sitolojia ya GYN (Pap smear)',
  organ_urineCytoSite: 'Sitolojia ya Mkojo',
  organ_csfSite: 'Majimaji ya uti wa mgongo (CSF)',
};

// ---------------------------------------------------------------------------
// Lookup maps: English name → translation key
// ---------------------------------------------------------------------------

export const SITE_KEY_MAP: Record<string, keyof typeof en> = {
  'Gastrointestinal (GI)': 'site_gi',
  'Hepatobiliary & Pancreas': 'site_hepatobiliary',
  'Breast': 'site_breast',
  'Gynecologic': 'site_gynecologic',
  'Urologic (GU)': 'site_urologic',
  'Head & Neck': 'site_headNeck',
  'Respiratory (Lung & Pleura)': 'site_respiratory',
  'Skin': 'site_skin',
  'Lymph Node / Hematolymphoid': 'site_lymph',
  'Bone & Soft Tissue': 'site_boneSoft',
  'Central Nervous System (CNS)': 'site_cns',
  'Placenta / Products of Conception': 'site_placenta',
  'GYN Cytology (Pap smears)': 'site_gynCyto',
  'Fine Needle Aspiration (FNA)': 'site_fna',
  'Fluid Cytology (Effusions)': 'site_fluidCyto',
  'Urine Cytology': 'site_urine',
  'Respiratory Cytology': 'site_respCyto',
  'CSF (Cerebrospinal fluid)': 'site_csf',
  'Body Fluid (Non-effusion)': 'site_bodyFluid',
};

export const ORGAN_KEY_MAP: Record<string, keyof typeof en> = {
  'Esophagus': 'organ_esophagus',
  'Stomach': 'organ_stomach',
  'Duodenum': 'organ_duodenum',
  'Small bowel (jejunum/ileum)': 'organ_smallBowel',
  'Colon': 'organ_colon',
  'Rectum': 'organ_rectum',
  'Appendix': 'organ_appendix',
  'Anus': 'organ_anus',
  'Liver': 'organ_liver',
  'Gallbladder': 'organ_gallbladder',
  'Bile duct': 'organ_bileDuct',
  'Pancreas': 'organ_pancreas',
  'Breast': 'organ_breast',
  'Axillary tissue': 'organ_axillary',
  'Cervix': 'organ_cervix',
  'Endometrium': 'organ_endometrium',
  'Myometrium': 'organ_myometrium',
  'Ovary': 'organ_ovary',
  'Fallopian tube': 'organ_fallopian',
  'Vulva': 'organ_vulva',
  'Vagina': 'organ_vagina',
  'Prostate': 'organ_prostate',
  'Bladder': 'organ_bladder',
  'Kidney': 'organ_kidney',
  'Ureter': 'organ_ureter',
  'Testis': 'organ_testis',
  'Epididymis': 'organ_epididymis',
  'Penis': 'organ_penis',
  'Oral cavity': 'organ_oralCavity',
  'Tongue': 'organ_tongue',
  'Salivary gland': 'organ_salivaryGland',
  'Thyroid': 'organ_thyroid',
  'Parathyroid': 'organ_parathyroid',
  'Larynx': 'organ_larynx',
  'Pharynx': 'organ_pharynx',
  'Nasal cavity / Sinus': 'organ_nasalSinus',
  'Neck (soft tissue/unspecified)': 'organ_neckSoftTissue',
  'Lung': 'organ_lung',
  'Pleura': 'organ_pleura',
  'Bronchus': 'organ_bronchus',
  'Skin': 'organ_skin',
  'Lymph node': 'organ_lymphNode',
  'Spleen': 'organ_spleen',
  'Bone marrow': 'organ_bonemarrow',
  'Bone': 'organ_bone',
  'Soft tissue': 'organ_softTissue',
  'Brain': 'organ_brain',
  'Spinal cord': 'organ_spinalCord',
  'Meninges': 'organ_meninges',
  'Placenta': 'organ_placenta',
  'Products of conception': 'organ_poc',
  'Pleural fluid': 'organ_pleuralFluid',
  'Ascitic fluid': 'organ_asciticFluid',
  'Pericardial fluid': 'organ_pericardialFluid',
  'Sputum': 'organ_sputum',
  'Bronchial wash': 'organ_bronchialWash',
  'Bronchial brush': 'organ_bronchialBrush',
  'BAL (bronchoalveolar lavage)': 'organ_bal',
  'Synovial fluid': 'organ_synovialFluid',
  'Cyst fluid': 'organ_cystFluid',
  'Other': 'organ_other',
  'GYN Cytology (Pap smears)': 'organ_gynCytoSite',
  'Urine Cytology': 'organ_urineCytoSite',
  'CSF (Cerebrospinal fluid)': 'organ_csfSite',
};

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

type TranslationKey = keyof typeof en;
type Translations = Readonly<Record<TranslationKey, string>>;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: keyof Translations) => string;
  tSite: (englishName: string) => string;
  tOrgan: (englishName: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const DICTS: Record<Lang, Translations> = { en, sw };

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const stored = (typeof localStorage !== 'undefined' ? localStorage.getItem('ap_lis_lang') : null) as Lang | null;
  const [lang, setLangState] = useState<Lang>(stored === 'sw' ? 'sw' : 'en');

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('ap_lis_lang', l);
  };

  const dict = DICTS[lang];
  const t = (key: keyof Translations) => dict[key] as string;
  const tSite = (name: string) => {
    const key = SITE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tOrgan = (name: string) => {
    const key = ORGAN_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tSite, tOrgan }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
