import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import { APP_LANGUAGE_CODES, type AppLanguageCode } from '@lis/shared';

export type Lang = AppLanguageCode;

export interface LanguageOption {
  code: Lang;
  label: string;
  nativeLabel: string;
  shortLabel: string;
  direction: 'ltr' | 'rtl';
}

export const LANGUAGE_OPTIONS: readonly LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', shortLabel: 'EN', direction: 'ltr' },
  { code: 'sw', label: 'Swahili', nativeLabel: 'Kiswahili', shortLabel: 'SW', direction: 'ltr' },
  { code: 'fr', label: 'French', nativeLabel: 'Français', shortLabel: 'FR', direction: 'ltr' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية', shortLabel: 'AR', direction: 'rtl' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو', shortLabel: 'UR', direction: 'rtl' },
] as const;

const LANGUAGE_OPTIONS_BY_CODE: Record<Lang, LanguageOption> = Object.fromEntries(
  LANGUAGE_OPTIONS.map((option) => [option.code, option])
) as Record<Lang, LanguageOption>;

// ---------------------------------------------------------------------------
// Translation dictionaries
// ---------------------------------------------------------------------------

const en = {
  // App
  appName: 'AP LIS',
  appFull: 'Anatomic Pathology Laboratory Information System',

  // Nav
  nav_home: 'Home',
  nav_orderEntry: 'Order Entry',
  nav_processing: 'Processing',
  nav_result: 'Result',
  nav_query: 'Query',
  nav_logout: 'Logout',

  // Common
  save: 'Save',
  delete: 'Delete',
  search: 'Search',
  cancel: 'Cancel',
  confirm: 'Confirm',
  close: 'Close',
  loading: 'Loading...',
  cases: 'cases',
  results: 'results',
  noResults: 'No matching cases found',
  errorGeneric: 'Something went wrong. Please try again.',

  // Login
  login_findEmployee: 'Find employee',
  login_newEmployee: 'New employee',
  login_searchPlaceholder: 'Search by name or username',
  login_noEmployeesFound: 'No employees found. Try creating a new one.',
  login_firstName: 'First Name',
  login_lastName: 'Last Name',
  login_username: 'Username',
  login_role: 'Role',
  role_pathologist: 'Pathologist',
  role_technologist: 'Technologist',
  login_createAndLogin: 'Create & Login',
  login_allFieldsRequired: 'All fields are required for a new employee',
  login_failed: 'Login failed. Please try again.',
  login_defaultLanguage: 'Default Language',
  input_keyboardLayoutHint: 'To type Arabic or Urdu text, switch your keyboard layout. Changing the app language does not change your keyboard alphabet.',

  // Dashboard
  dash_workflow: 'Workflow',
  dash_orderEntry_title: 'Order Entry',
  dash_orderEntry_desc: 'Register a new pathology case. Enter patient and clinician details, add specimens, and generate the case worksheet.',
  dash_processing_title: 'Processing Queue',
  dash_processing_desc: 'Cases awaiting grossing and block/slide preparation. Select a case to record blocks and slides for each specimen.',
  dash_result_title: 'Result Queue',
  dash_result_desc: 'Cases with slides prepared, ready for microscopic examination and reporting. Sign out completed cases here.',
  dash_query_title: 'Query',
  dash_query_desc: 'Search for any case by case ID or patient ID to review its current status, materials, and reports.',
  dash_systemDesc: 'A lightweight workflow management system for anatomic pathology laboratories. Track cases from initial registration through grossing, slide preparation, microscopic examination, and final sign-out.',
  dash_loggedInAs: 'Logged in as',

  // Processing Queue
  pq_title: 'Processing Queue',
  pq_searchPlaceholder: 'Search case ID, patient ID or patient name',
  pq_showAll: 'Show all (including completed)',
  pq_caseId: 'Case ID',
  pq_patient: 'Patient',
  pq_clinician: 'Clinician',
  pq_registered: 'Registered',
  pq_type: 'Type',
  pq_specimens: 'Specimens',
  pq_noCases: 'No cases in queue',

  // Result Queue
  rq_title: 'Result Queue',
  rq_pendingResult: 'Pending Result',
  rq_reactivated: 'Reactivated',
  rq_status: 'Status',
  rq_noCases: 'No cases pending result',

  // Query
  q_title: 'Query',
  q_caseId: 'Case ID',
  q_patientId: 'Patient ID',
  q_search: 'Search',
  q_status: 'Status',
  q_signedOut: 'Signed Out',
  q_inProgress: 'In Progress',
  q_noResults: 'No matching cases found',
  q_error: 'Search failed. Please try again.',
  q_searchFailed: 'Search failed. Please try again.',

  // Order Entry
  oe_title: 'Order Entry',
  oe_patient: 'Patient',
  oe_existing: 'Existing',
  oe_new: 'New',
  oe_searchPatient: 'Search patient',
  oe_searchClinician: 'Search clinician',
  oe_clinician: 'Clinician',
  oe_caseDetails: 'Case Details',
  oe_caseType: 'Case Type',
  oe_surgicalPathology: 'Surgical Pathology',
  oe_cytology: 'Cytology',
  oe_specimens: 'Specimens',
  oe_addSpecimen: 'Add Specimen',
  oe_specimen: 'Specimen',
  oe_site: 'Site',
  oe_organ: 'Organ',
  oe_specimenType: 'Specimen Type',
  oe_coldIschemicTime: 'Cold Ischemic Time (min)',
  oe_createCase: 'Create Case',
  oe_caseCreated: 'Case created:',
  oe_worksheetPdf: 'Worksheet PDF',
  oe_sex: 'Sex',
  oe_dob: 'Date of Birth',
  oe_firstName: 'First Name',
  oe_lastName: 'Last Name',
  oe_dateOfBirth: 'Date of Birth',
  oe_sexMale: 'Male',
  oe_sexFemale: 'Female',
  oe_sexOther: 'Other',
  oe_sexUnknown: 'Unknown',
  specimenType_biopsy: 'Biopsy',
  specimenType_excision: 'Excision',
  specimenType_resection: 'Resection',
  specimenType_cytology: 'Cytology',
  specimenType_coreNeedleBiopsy: 'Core needle biopsy',
  specimenType_fineNeedleAspiration: 'Fine needle aspiration',
  specimenType_curettage: 'Curettage',
  specimenType_polypectomy: 'Polypectomy',
  specimenType_amputation: 'Amputation',
  specimenType_boneMarrowBiopsy: 'Bone marrow biopsy',
  slideType_he: 'H&E',
  slideType_unstained: 'Unstained',
  slideType_ihc: 'IHC',
  slideType_specialStain: 'Special stain',
  slideType_other: 'Other',

  // Processing Case
  pc_referenceStrips: 'Reference Strips PDF',
  pc_referenceStripsPdf: 'Reference Strips PDF',
  pc_save: 'Save',
  pc_saveAndExit: 'Save & Exit',
  pc_saved: 'Case saved',
  pc_caseSaved: 'Case saved',
  pc_saveFailed: 'Failed to save case',
  pc_clinicalHistory: 'Clinical History',
  pc_grossDescription: 'Gross Description',
  pc_openResults: 'Open Results',
  pc_materials: 'Materials',
  pc_noSpecimens: 'No specimens found for this case.',
  pc_blockId: 'Block ID',
  pc_slides: 'Slides',
  pc_addSlides: 'Add Slides',
  pc_addSlidesHeader: 'Add Slides',
  pc_deleteBlock: 'Delete block and all its slides',
  pc_deleteBlockTooltip: 'Delete block and all its slides',
  common_delete: 'Delete',
  pc_numBlocks: '# Blocks',
  pc_numSlides: '# Slides',
  pc_addBlock: 'Add Block',
  pc_addBlocks: 'Add Blocks',
  pc_addSlide: 'Add Slide',
  pc_addSlidesBtn: 'Add Slides',
  pc_noSlides: 'none',
  pc_none: 'none',
  pc_noSlidesYet: 'No slides yet',
  pc_slideType: 'Type',

  // Result Case
  rc_processing: 'Processing',
  rc_finalDiagnosis: 'Final Diagnosis',
  rc_comment: 'Comment',
  rc_microscopicDescription: 'Microscopic Description',
  rc_grossDescription: 'Gross Description',
  rc_clinicalHistory: 'Clinical History',
  rc_capTemplate: 'CAP Template (optional)',
  rc_reportingTemplate: 'Reporting Template',
  rc_grossTemplate: 'Gross Template',
  rc_microscopicContent: 'Microscopic Description',
  rc_saveDraft: 'Save Draft',
  rc_saveAndExit: 'Save & Exit',
  rc_exit: 'Exit',
  rc_signOut: 'Sign Out',
  rc_reactivate: 'Reactivate',
  rc_signedOut: 'Signed Out',
  rc_draftSaved: 'Draft saved',
  rc_historySaved: 'Clinical history saved',
  rc_clinicalHistorySaved: 'Clinical history saved',
  rc_report: 'Report',
  rc_history: 'History',
  rc_materials: 'Materials',
  rc_reportPdf: 'Report PDF',
  rc_amendedPdf: 'Amended PDF',
  rc_confirmSignOut: 'Confirm Sign-Out',
  rc_confirmSignOutMsg: 'This action is final. The report will become immutable once signed out.',
  rc_confirmReactivate: 'Confirm Reactivation',
  rc_confirmReactivateMsg: 'This will reactivate the case for amendment. Are you sure?',
  rc_version: 'Version',
  rc_pathologist: 'Pathologist',
  rc_date: 'Date',
  rc_signedOutStatus: 'Signed Out',
  rc_inProgress: 'In Progress',
  rc_saveHistory: 'Save History',
  rc_signedOutAlert: 'This case is signed out. Use Reactivate to create a revision or addendum.',
  rc_viewReportPdf: 'View Report PDF',
  rc_capTemplatePlaceholder: 'Select a CAP template above, then fill in the fields',
  rc_dob: 'DOB',
  rc_sex: 'Sex',
  rc_resultEntry: 'Result Entry',
  rc_reportHistory: 'Report History',
  rc_reactivateCase: 'Reactivate Case',
  rc_reactivateMsg: 'Reactivating will create a new draft report. Prior reports remain immutable.',
  rc_revise: 'Revise',
  rc_revision: 'Revision',
  rc_addend: 'Addend',
  rc_none: 'None',
  rc_final: 'Final',
  rc_draft: 'Draft',
  rc_prelim: 'Prelim',
  rc_signedOutSuccess: 'Report signed out successfully',
  rc_reactivatedSuccess: 'Case reactivated. A new draft has been created.',
  rc_signPrelim: 'Sign Prelim',
  rc_confirmSignPrelim: 'Confirm Preliminary Sign-Out',
  rc_confirmSignPrelimMsg: 'This will generate a Preliminary Report PDF. The case will remain active for further editing.',
  rc_signedPrelimSuccess: 'Preliminary report generated. Case remains active.',
  rc_viewPrelimPdf: 'View Prelim PDF',
  rc_openProcessing: 'Open Processing',
  rc_reactivateExplanation: 'Explanation (required)',
  rc_reactivateExplanationPlaceholder: 'Provide reason for reactivation or addendum...',
  rc_templateLoading: 'Loading template...',
  rc_templateUnavailable: 'Template unavailable. You can continue editing the generated text directly.',
  nav_unsavedTitle: 'Unsaved Changes',
  nav_unsavedChanges: 'You have unsaved changes. Are you sure you want to leave?',
  nav_leave: 'Leave',
  nav_stay: 'Stay',

  // Body sites (surgical)
  site_gi: 'Gastrointestinal (GI)',
  site_hepatobiliary: 'Hepatobiliary & Pancreas',
  site_breast: 'Breast',
  site_gynecologic: 'Gynecologic',
  site_urologic: 'Urologic (GU)',
  site_headNeck: 'Head & Neck',
  site_respiratory: 'Respiratory (Lung & Pleura)',
  site_skin: 'Skin',
  site_lymph: 'Lymph Node / Hematolymphoid',
  site_boneSoft: 'Bone & Soft Tissue',
  site_cns: 'Central Nervous System (CNS)',
  site_placenta: 'Placenta / Products of Conception',

  // Cytology sites
  site_gynCyto: 'GYN Cytology (Pap smears)',
  site_fna: 'Fine Needle Aspiration (FNA)',
  site_fluidCyto: 'Fluid Cytology (Effusions)',
  site_urine: 'Urine Cytology',
  site_respCyto: 'Respiratory Cytology',
  site_csf: 'CSF (Cerebrospinal fluid)',
  site_bodyFluid: 'Body Fluid (Non-effusion)',

  // Organs (surgical)
  organ_esophagus: 'Esophagus',
  organ_stomach: 'Stomach',
  organ_duodenum: 'Duodenum',
  organ_smallBowel: 'Small bowel (jejunum/ileum)',
  organ_colon: 'Colon',
  organ_rectum: 'Rectum',
  organ_appendix: 'Appendix',
  organ_anus: 'Anus',
  organ_liver: 'Liver',
  organ_gallbladder: 'Gallbladder',
  organ_bileDuct: 'Bile duct',
  organ_pancreas: 'Pancreas',
  organ_breast: 'Breast',
  organ_axillary: 'Axillary tissue',
  organ_cervix: 'Cervix',
  organ_endometrium: 'Endometrium',
  organ_myometrium: 'Myometrium',
  organ_ovary: 'Ovary',
  organ_fallopian: 'Fallopian tube',
  organ_vulva: 'Vulva',
  organ_vagina: 'Vagina',
  organ_prostate: 'Prostate',
  organ_bladder: 'Bladder',
  organ_kidney: 'Kidney',
  organ_ureter: 'Ureter',
  organ_testis: 'Testis',
  organ_epididymis: 'Epididymis',
  organ_penis: 'Penis',
  organ_oralCavity: 'Oral cavity',
  organ_tongue: 'Tongue',
  organ_salivaryGland: 'Salivary gland',
  organ_thyroid: 'Thyroid',
  organ_parathyroid: 'Parathyroid',
  organ_larynx: 'Larynx',
  organ_pharynx: 'Pharynx',
  organ_nasalSinus: 'Nasal cavity / Sinus',
  organ_neckSoftTissue: 'Neck (soft tissue/unspecified)',
  organ_lung: 'Lung',
  organ_pleura: 'Pleura',
  organ_bronchus: 'Bronchus',
  organ_skin: 'Skin',
  organ_lymphNode: 'Lymph node',
  organ_spleen: 'Spleen',
  organ_bonemarrow: 'Bone marrow',
  organ_bone: 'Bone',
  organ_softTissue: 'Soft tissue',
  organ_brain: 'Brain',
  organ_spinalCord: 'Spinal cord',
  organ_meninges: 'Meninges',
  organ_placenta: 'Placenta',
  organ_poc: 'Products of conception',

  // Cytology organs / sub-sites
  organ_pleuralFluid: 'Pleural fluid',
  organ_asciticFluid: 'Ascitic fluid',
  organ_pericardialFluid: 'Pericardial fluid',
  organ_sputum: 'Sputum',
  organ_bronchialWash: 'Bronchial wash',
  organ_bronchialBrush: 'Bronchial brush',
  organ_bal: 'BAL (bronchoalveolar lavage)',
  organ_synovialFluid: 'Synovial fluid',
  organ_cystFluid: 'Cyst fluid',
  organ_other: 'Other',
  organ_gynCytoSite: 'GYN Cytology (Pap smears)',
  organ_urineCytoSite: 'Urine Cytology',
  organ_csfSite: 'CSF (Cerebrospinal fluid)',

  // Configuration — Template Manager
  nav_config: 'Configuration',
  cfg_title: 'Template Manager',
  cfg_new: 'New Template',
  cfg_save: 'Save',
  cfg_saving: 'Saving...',
  cfg_saved: 'Template saved',
  cfg_saveFailed: 'Failed to save template',
  cfg_created: 'Template created',
  cfg_createFailed: 'Failed to create template',
  cfg_clone: 'Clone Template',
  cfg_coreTab: 'Core (EN)',
  cfg_filterPlaceholder: 'Filter templates...',
  cfg_noTemplates: 'No templates found',
  cfg_invalidJson: 'Invalid JSON',
  cfg_preview: 'Preview',
  cfg_selectTemplate: 'Select a template to edit',
  cfg_kind: 'Kind',
  cfg_family: 'Family',
  cfg_templateKey: 'Template Key',
  cfg_templateKeyHint: 'e.g. breast.histology/breast/reporting/my_template',
  cfg_blank: 'Blank template',
  cfg_cloneExisting: 'Clone existing template',
  cfg_cloneSource: 'Clone from',
  cfg_step1Setup: 'Setup',
  cfg_step2Edit: 'Edit JSON',
  cfg_create: 'Create',
  cfg_gross: 'Gross',
  cfg_reporting: 'Reporting',
  cfg_directory: 'Directory',
  cfg_filename: 'Filename',
  cfg_tabTemplates: 'Template Manager',
  cfg_tabReports: 'Report Manager',
  rpt_title: 'Report Manager',
  rpt_final: 'Final',
  rpt_preliminary: 'Preliminary',
  rpt_addendum: 'Addendum',
  rpt_revision: 'Revision',
  rpt_layoutName: 'Layout Name',
  rpt_htmlTemplate: 'HTML Template',
  rpt_active: 'Active',
  rpt_save: 'Save',
  rpt_saved: 'Layout saved',
  rpt_saveFailed: 'Failed to save layout',
  rpt_reset: 'Reset to Default',
  rpt_resetConfirm: 'Reset this layout to the built-in default template?',
  rpt_resetDone: 'Layout reset to default',
  rpt_preview: 'Preview PDF',
  rpt_previewNote: 'Preview rendered with sample data',
  rpt_templateVars: 'Template Variables',
  rpt_selectLayout: 'Select a report type to edit its layout',
  rpt_noLayout: 'No layout defined',
} as const;

const sw: Record<keyof typeof en, string> = {
  appName: 'AP LIS',
  appFull: 'Mfumo wa Habari wa Maabara ya Patholojia',

  nav_home: 'Nyumbani',
  nav_orderEntry: 'Kuingiza Oda',
  nav_processing: 'Kusindika',
  nav_result: 'Matokeo',
  nav_query: 'Utafutaji',
  nav_logout: 'Toka',

  save: 'Hifadhi',
  delete: 'Futa',
  search: 'Tafuta',
  cancel: 'Ghairi',
  confirm: 'Thibitisha',
  close: 'Funga',
  loading: 'Inapakia...',
  cases: 'kesi',
  results: 'matokeo',
  noResults: 'Hakuna kesi zinazolingana',
  errorGeneric: 'Hitilafu imetokea. Tafadhali jaribu tena.',

  login_findEmployee: 'Tafuta mfanyakazi',
  login_newEmployee: 'Mfanyakazi mpya',
  login_searchPlaceholder: 'Tafuta kwa jina au jina la mtumiaji',
  login_noEmployeesFound: 'Hakuna mfanyakazi aliyepatikana. Jaribu kuunda mpya.',
  login_firstName: 'Jina la Kwanza',
  login_lastName: 'Jina la Familia',
  login_username: 'Jina la Mtumiaji',
  login_role: 'Jukumu',
  role_pathologist: 'Daktari wa Patholojia',
  role_technologist: 'Teknolojia wa Maabara',
  login_createAndLogin: 'Unda & Ingia',
  login_allFieldsRequired: 'Sehemu zote zinahitajika kwa mfanyakazi mpya',
  login_failed: 'Kuingia kumeshindwa. Tafadhali jaribu tena.',
  login_defaultLanguage: 'Lugha ya Msingi',
  input_keyboardLayoutHint: 'Ili kuandika maandishi ya Kiarabu au Kiurdu, badili mpangilio wa kibodi yako. Kubadili lugha ya programu hakubadili alfabeti ya kibodi.',

  dash_workflow: 'Mtiririko wa Kazi',
  dash_orderEntry_title: 'Kuingiza Oda',
  dash_orderEntry_desc: 'Sajili kesi mpya ya patholojia. Weka taarifa za mgonjwa na daktari, ongeza sampuli, na uzalishe karatasi ya kazi.',
  dash_processing_title: 'Foleni ya Kusindika',
  dash_processing_desc: 'Kesi zinazosubiri kuchunguzwa kwa macho na kuandaa blocks/slides. Chagua kesi ili kurekodi blocks na slides kwa kila sampuli.',
  dash_result_title: 'Foleni ya Matokeo',
  dash_result_desc: 'Kesi zenye slides zikiwa tayari kwa uchunguzi wa darubini na kuandika ripoti. Sahihi kesi zilizokamilika hapa.',
  dash_query_title: 'Utafutaji',
  dash_query_desc: 'Tafuta kesi yoyote kwa nambari ya kesi au nambari ya mgonjwa ili kukagua hali yake ya sasa, vifaa, na ripoti.',
  dash_systemDesc: 'Mfumo mwepesi wa usimamizi wa mtiririko wa kazi kwa maabara za patholojia ya anatomiki. Fuatilia kesi kuanzia usajili kupitia kuchunguza kwa macho ya nje, kuandaa slides, uchunguzi wa darubini, na kutoa sahihi ya mwisho.',
  dash_loggedInAs: 'Umeingia kama',

  pq_title: 'Foleni ya Kusindika',
  pq_searchPlaceholder: 'Tafuta nambari ya kesi, kitambulisho au jina la mgonjwa',
  pq_showAll: 'Onyesha zote (pamoja na zilizokamilika)',
  pq_caseId: 'Nambari ya Kesi',
  pq_patient: 'Mgonjwa',
  pq_clinician: 'Daktari',
  pq_registered: 'Ilisajiliwa',
  pq_type: 'Aina',
  pq_specimens: 'Sampuli',
  pq_noCases: 'Hakuna kesi kwenye foleni',

  rq_title: 'Foleni ya Matokeo',
  rq_pendingResult: 'Inasubiri Matokeo',
  rq_reactivated: 'Imeanzishwa Upya',
  rq_status: 'Hali',
  rq_noCases: 'Hakuna kesi zinazosubiri matokeo',

  q_title: 'Utafutaji',
  q_caseId: 'Nambari ya Kesi',
  q_patientId: 'Nambari ya Mgonjwa',
  q_search: 'Tafuta',
  q_status: 'Hali',
  q_signedOut: 'Imetolewa Sahihi',
  q_inProgress: 'Inaendelea',
  q_noResults: 'Hakuna kesi zinazolingana',
  q_error: 'Utafutaji umeshindwa. Tafadhali jaribu tena.',
  q_searchFailed: 'Utafutaji umeshindwa. Tafadhali jaribu tena.',

  oe_title: 'Kuingiza Oda',
  oe_patient: 'Mgonjwa',
  oe_existing: 'Aliyepo',
  oe_new: 'Mpya',
  oe_searchPatient: 'Tafuta mgonjwa',
  oe_searchClinician: 'Tafuta daktari',
  oe_clinician: 'Daktari',
  oe_caseDetails: 'Maelezo ya Kesi',
  oe_caseType: 'Aina ya Kesi',
  oe_surgicalPathology: 'Upasuaji',
  oe_cytology: 'Sitolojia',
  oe_specimens: 'Sampuli',
  oe_addSpecimen: 'Ongeza Sampuli',
  oe_specimen: 'Sampuli',
  oe_site: 'Sehemu ya Mwili',
  oe_organ: 'Kiungo',
  oe_specimenType: 'Aina ya Sampuli',
  oe_coldIschemicTime: 'Muda wa Cold Ischemic (dak)',
  oe_createCase: 'Unda Kesi',
  oe_caseCreated: 'Kesi imeundwa:',
  oe_worksheetPdf: 'PDF ya Karatasi ya Kazi',
  oe_sex: 'Jinsia',
  oe_dob: 'Tarehe ya Kuzaliwa',
  oe_firstName: 'Jina la Kwanza',
  oe_lastName: 'Jina la Familia',
  oe_dateOfBirth: 'Tarehe ya Kuzaliwa',
  oe_sexMale: 'Mwanaume',
  oe_sexFemale: 'Mwanamke',
  oe_sexOther: 'Nyingine',
  oe_sexUnknown: 'Haijulikani',
  specimenType_biopsy: 'Biopsy',
  specimenType_excision: 'Excision',
  specimenType_resection: 'Resection',
  specimenType_cytology: 'Sitolojia',
  specimenType_coreNeedleBiopsy: 'Biopsy ya sindano ya core',
  specimenType_fineNeedleAspiration: 'Aspirati ya sindano nyembamba',
  specimenType_curettage: 'Kurettaji',
  specimenType_polypectomy: 'Uondoaji wa polypi',
  specimenType_amputation: 'Ukataji kiungo',
  specimenType_boneMarrowBiopsy: 'Biopsy ya uboho',
  slideType_he: 'H&E',
  slideType_unstained: 'Isiyo na rangi',
  slideType_ihc: 'IHC',
  slideType_specialStain: 'Rangi maalum',
  slideType_other: 'Nyingine',

  pc_referenceStrips: 'PDF ya Kumbukumbu',
  pc_referenceStripsPdf: 'PDF ya Kumbukumbu',
  pc_save: 'Hifadhi',
  pc_saveAndExit: 'Hifadhi na Toka',
  pc_saved: 'Kesi imehifadhiwa',
  pc_caseSaved: 'Kesi imehifadhiwa',
  pc_saveFailed: 'Imeshindwa kuhifadhi kesi',
  pc_clinicalHistory: 'Historia ya Mgonjwa',
  pc_grossDescription: 'Maelezo ya Gross',
  pc_openResults: 'Fungua Matokeo',
  pc_materials: 'Vifaa',
  pc_noSpecimens: 'Hakuna sampuli zilizopatikana kwa kesi hii.',
  pc_blockId: 'Nambari ya Block',
  pc_slides: 'Slides',
  pc_addSlides: 'Ongeza Slides',
  pc_addSlidesHeader: 'Ongeza Slides',
  pc_deleteBlock: 'Futa block na slides zake zote',
  pc_deleteBlockTooltip: 'Futa block na slides zake zote',
  common_delete: 'Futa',
  pc_numBlocks: 'Idadi ya Blocks',
  pc_numSlides: 'Idadi ya Slides',
  pc_addBlock: 'Ongeza Block',
  pc_addBlocks: 'Ongeza Blocks',
  pc_addSlide: 'Ongeza Slide',
  pc_addSlidesBtn: 'Ongeza Slides',
  pc_noSlides: 'hakuna',
  pc_none: 'hakuna',
  pc_noSlidesYet: 'Bado hakuna slides',
  pc_slideType: 'Aina',

  rc_processing: 'Kusindika',
  rc_finalDiagnosis: 'Utambuzi wa Mwisho',
  rc_comment: 'Maoni',
  rc_microscopicDescription: 'Maelezo ya Microscopy',
  rc_grossDescription: 'Maelezo ya Gross',
  rc_clinicalHistory: 'Historia ya Mgonjwa',
  rc_capTemplate: 'Kiolezo cha CAP (hiari)',
  rc_reportingTemplate: 'Kiolezo cha Ripoti',
  rc_grossTemplate: 'Kiolezo cha Gross',
  rc_microscopicContent: 'Maelezo ya Microscopy',
  rc_saveDraft: 'Hifadhi Rasimu',
  rc_saveAndExit: 'Hifadhi na Toka',
  rc_exit: 'Toka',
  rc_signOut: 'Toa Sahihi',
  rc_reactivate: 'Anzisha Upya',
  rc_signedOut: 'Imetolewa Sahihi',
  rc_draftSaved: 'Rasimu imehifadhiwa',
  rc_historySaved: 'Historia ya mgonjwa imehifadhiwa',
  rc_clinicalHistorySaved: 'Historia ya mgonjwa imehifadhiwa',
  rc_report: 'Ripoti',
  rc_history: 'Historia',
  rc_materials: 'Vifaa',
  rc_reportPdf: 'PDF ya Ripoti',
  rc_amendedPdf: 'PDF Iliyorekebishwa',
  rc_confirmSignOut: 'Thibitisha Kutoa Sahihi',
  rc_confirmSignOutMsg: 'Hatua hii ni ya mwisho. Ripoti itakuwa haiwezi kubadilishwa baada ya kutolewa sahihi.',
  rc_confirmReactivate: 'Thibitisha Kuanzisha Upya',
  rc_confirmReactivateMsg: 'Hii itaanzisha upya kesi kwa urekebishaji. Je, una uhakika?',
  rc_version: 'Toleo',
  rc_pathologist: 'Daktari wa Patholojia',
  rc_date: 'Tarehe',
  rc_signedOutStatus: 'Imetolewa Sahihi',
  rc_inProgress: 'Inaendelea',
  rc_saveHistory: 'Hifadhi Historia',
  rc_signedOutAlert: 'Kesi hii imetolewa sahihi. Tumia Anzisha Upya kuunda toleo jipya au kiongezeko.',
  rc_viewReportPdf: 'Tazama PDF ya Ripoti',
  rc_capTemplatePlaceholder: 'Chagua kiolezo cha CAP hapo juu, kisha jaza sehemu',
  rc_dob: 'Tarehe ya Kuzaliwa',
  rc_sex: 'Jinsia',
  rc_resultEntry: 'Kuingiza Matokeo',
  rc_reportHistory: 'Historia ya Ripoti',
  rc_reactivateCase: 'Anzisha Upya Kesi',
  rc_reactivateMsg: 'Kuanzisha upya kutaunda rasimu mpya ya ripoti. Ripoti za awali hazibadiliki.',
  rc_revise: 'Rekebisha',
  rc_revision: 'Marekebisho',
  rc_addend: 'Ongeza',
  rc_none: 'Hakuna',
  rc_final: 'ya Mwisho',
  rc_draft: 'Rasimu',
  rc_prelim: 'Awali',
  rc_signedOutSuccess: 'Ripoti imetolewa sahihi',
  rc_reactivatedSuccess: 'Kesi imeanzishwa upya. Rasimu mpya imeundwa.',
  rc_signPrelim: 'Saini Awali',
  rc_confirmSignPrelim: 'Thibitisha Kutoa Ripoti ya Awali',
  rc_confirmSignPrelimMsg: 'Hii itaunda PDF ya Ripoti ya Awali. Kesi itabaki wazi kwa mabadiliko zaidi.',
  rc_signedPrelimSuccess: 'Ripoti ya awali imeundwa. Kesi iko wazi.',
  rc_viewPrelimPdf: 'Tazama PDF ya Awali',
  rc_openProcessing: 'Fungua Kusindika',
  rc_reactivateExplanation: 'Maelezo (inahitajika)',
  rc_reactivateExplanationPlaceholder: 'Toa sababu ya kuanzisha upya au kuongeza...',
  rc_templateLoading: 'Inapakia kiolezo...',
  rc_templateUnavailable: 'Kiolezo hakipatikani. Unaweza kuendelea kuhariri maandishi yaliyotengenezwa moja kwa moja.',
  nav_unsavedTitle: 'Mabadiliko Hayajahifadhiwa',
  nav_unsavedChanges: 'Una mabadiliko ambayo hayajahifadhiwa. Je, una uhakika unataka kuondoka?',
  nav_leave: 'Ondoka',
  nav_stay: 'Kaa',

  // Body sites
  site_gi: 'Mfumo wa Mmeng\'enyo wa Chakula (GI)',
  site_hepatobiliary: 'Ini, Njia ya Nyongo & Kongosho',
  site_breast: 'Matiti',
  site_gynecologic: 'Mfumo wa Uzazi wa Mwanamke',
  site_urologic: 'Mfumo wa Mkojo na Uzazi wa Mwanaume (GU)',
  site_headNeck: 'Kichwa na Shingo',
  site_respiratory: 'Mfumo wa Upumuaji (Mapafu na Pleura)',
  site_skin: 'Ngozi',
  site_lymph: 'Tezi za Limfu / Mfumo wa Damu na Limfu',
  site_boneSoft: 'Mfupa na Tishu Laini',
  site_cns: 'Mfumo wa Neva wa Kati (CNS)',
  site_placenta: 'Kondo la Nyuma / Mabaki ya Ujauzito',

  site_gynCyto: 'Sitolojia ya GYN (Pap smear)',
  site_fna: 'Fine Needle Aspiration (FNA)',
  site_fluidCyto: 'Sitolojia ya Majimaji (Effusions)',
  site_urine: 'Sitolojia ya Mkojo',
  site_respCyto: 'Sitolojia ya Mfumo wa Upumuaji',
  site_csf: 'Majimaji ya uti wa mgongo (CSF)',
  site_bodyFluid: 'Majimaji ya Mwili (yasiyo effusion)',

  // Organs
  organ_esophagus: 'Umio (Esophagus)',
  organ_stomach: 'Tumbo (Stomach)',
  organ_duodenum: 'Duodenum',
  organ_smallBowel: 'Utumbo mdogo (jejunum/ileum)',
  organ_colon: 'Utumbo mpana (Colon)',
  organ_rectum: 'Rektamu',
  organ_appendix: 'Appendix',
  organ_anus: 'Mkundu (Anus)',
  organ_liver: 'Ini',
  organ_gallbladder: 'Kibofu cha nyongo',
  organ_bileDuct: 'Njia ya nyongo',
  organ_pancreas: 'Kongosho',
  organ_breast: 'Titi',
  organ_axillary: 'Tishu za kwapa',
  organ_cervix: 'Shingo ya kizazi (Cervix)',
  organ_endometrium: 'Uterasi (Endometrium)',
  organ_myometrium: 'Misuli ya uterasi (Myometrium)',
  organ_ovary: 'Ovari',
  organ_fallopian: 'Mirija ya fallopian',
  organ_vulva: 'Vulva',
  organ_vagina: 'Uke (Vagina)',
  organ_prostate: 'Prostate',
  organ_bladder: 'Kibofu cha mkojo',
  organ_kidney: 'Figo',
  organ_ureter: 'Ureta',
  organ_testis: 'Korodani (Testis)',
  organ_epididymis: 'Epididymis',
  organ_penis: 'Uume',
  organ_oralCavity: 'Mdomo (Oral cavity)',
  organ_tongue: 'Ulimi',
  organ_salivaryGland: 'Tezi za mate',
  organ_thyroid: 'Tezi ya thyroid',
  organ_parathyroid: 'Tezi ya parathyroid',
  organ_larynx: 'Larynx',
  organ_pharynx: 'Pharynx',
  organ_nasalSinus: 'Pua / Sinasi',
  organ_neckSoftTissue: 'Shingo (tishu laini/isiyobainishwa)',
  organ_lung: 'Pafu',
  organ_pleura: 'Pleura',
  organ_bronchus: 'Bronchus',
  organ_skin: 'Ngozi',
  organ_lymphNode: 'Tezi ya limfu',
  organ_spleen: 'Wengu (Spleen)',
  organ_bonemarrow: 'Uboho wa mfupa',
  organ_bone: 'Mfupa',
  organ_softTissue: 'Tishu laini',
  organ_brain: 'Ubongo',
  organ_spinalCord: 'Uti wa mgongo',
  organ_meninges: 'Utando wa ubongo (Meninges)',
  organ_placenta: 'Kondo la nyuma',
  organ_poc: 'Mabaki ya ujauzito',

  organ_pleuralFluid: 'Majimaji ya pleura',
  organ_asciticFluid: 'Majimaji ya tumbo (ascitic fluid)',
  organ_pericardialFluid: 'Majimaji ya moyo (pericardial fluid)',
  organ_sputum: 'Makamasi (Sputum)',
  organ_bronchialWash: 'Bronchial wash',
  organ_bronchialBrush: 'Bronchial brush',
  organ_bal: 'BAL (bronchoalveolar lavage)',
  organ_synovialFluid: 'Majimaji ya viungo (Synovial fluid)',
  organ_cystFluid: 'Majimaji ya uvimbe (Cyst fluid)',
  organ_other: 'Nyingine',
  organ_gynCytoSite: 'Sitolojia ya GYN (Pap smear)',
  organ_urineCytoSite: 'Sitolojia ya Mkojo',
  organ_csfSite: 'Majimaji ya uti wa mgongo (CSF)',

  // Configuration — Template Manager
  nav_config: 'Mipangilio',
  cfg_title: 'Msimamizi wa Violezo',
  cfg_new: 'Kiolezo Kipya',
  cfg_save: 'Hifadhi',
  cfg_saving: 'Inahifadhi...',
  cfg_saved: 'Kiolezo kimehifadhiwa',
  cfg_saveFailed: 'Imeshindwa kuhifadhi kiolezo',
  cfg_created: 'Kiolezo kimeundwa',
  cfg_createFailed: 'Imeshindwa kuunda kiolezo',
  cfg_clone: 'Nakili Kiolezo',
  cfg_coreTab: 'Msingi (EN)',
  cfg_filterPlaceholder: 'Chuja violezo...',
  cfg_noTemplates: 'Hakuna violezo vilivyopatikana',
  cfg_invalidJson: 'JSON batili',
  cfg_preview: 'Hakiki',
  cfg_selectTemplate: 'Chagua kiolezo cha kuhariri',
  cfg_kind: 'Aina',
  cfg_family: 'Familia',
  cfg_templateKey: 'Ufunguo wa Kiolezo',
  cfg_templateKeyHint: 'mfano: breast.histology/breast/reporting/my_template',
  cfg_blank: 'Kiolezo tupu',
  cfg_cloneExisting: 'Nakili kiolezo kilichopo',
  cfg_cloneSource: 'Nakili kutoka',
  cfg_step1Setup: 'Usanidi',
  cfg_step2Edit: 'Hariri JSON',
  cfg_create: 'Unda',
  cfg_gross: 'Gross',
  cfg_reporting: 'Ripoti',
  cfg_directory: 'Saraka',
  cfg_filename: 'Jina la faili',
  cfg_tabTemplates: 'Msimamizi wa Violezo',
  cfg_tabReports: 'Msimamizi wa Ripoti',
  rpt_title: 'Msimamizi wa Ripoti',
  rpt_final: 'Ya Mwisho',
  rpt_preliminary: 'Ya Awali',
  rpt_addendum: 'Nyongeza',
  rpt_revision: 'Marekebisho',
  rpt_layoutName: 'Jina la Mpangilio',
  rpt_htmlTemplate: 'Kiolezo cha HTML',
  rpt_active: 'Hai',
  rpt_save: 'Hifadhi',
  rpt_saved: 'Mpangilio umehifadhiwa',
  rpt_saveFailed: 'Imeshindwa kuhifadhi mpangilio',
  rpt_reset: 'Rejesha Chaguo-msingi',
  rpt_resetConfirm: 'Rejesha mpangilio huu kwenye kiolezo cha msingi kilichojengwa ndani?',
  rpt_resetDone: 'Mpangilio umeirejesha kwa chaguo-msingi',
  rpt_preview: 'Hakiki PDF',
  rpt_previewNote: 'Hakiki inayotolewa na data ya sampuli',
  rpt_templateVars: 'Vigezo vya Kiolezo',
  rpt_selectLayout: 'Chagua aina ya ripoti kuhariri mpangilio wake',
  rpt_noLayout: 'Hakuna mpangilio uliofafanuliwa',
};

const fr: Record<keyof typeof en, string> = {
  ...en,
  cases: 'cas',
  results: 'résultats',
  nav_home: 'Accueil',
  nav_orderEntry: 'Saisie',
  nav_processing: 'Traitement',
  nav_result: 'Résultat',
  nav_query: 'Recherche',
  nav_logout: 'Déconnexion',
  login_findEmployee: 'Trouver un employé',
  login_newEmployee: 'Nouvel employé',
  login_searchPlaceholder: 'Rechercher par nom ou identifiant',
  login_noEmployeesFound: 'Aucun employé trouvé. Essayez d’en créer un nouveau.',
  login_firstName: 'Prénom',
  login_lastName: 'Nom',
  login_username: 'Nom d’utilisateur',
  login_role: 'Rôle',
  role_pathologist: 'Pathologiste',
  role_technologist: 'Technologiste',
  login_createAndLogin: 'Créer et se connecter',
  login_allFieldsRequired: 'Tous les champs sont requis pour un nouvel employé',
  login_failed: 'Échec de la connexion. Veuillez réessayer.',
  login_defaultLanguage: 'Langue par défaut',
  input_keyboardLayoutHint: 'Pour saisir du texte en arabe ou en ourdou, changez la disposition de votre clavier. Changer la langue de l’application ne modifie pas l’alphabet du clavier.',
  appFull: 'Système d\'information de laboratoire d\'anatomie pathologique',
  dash_workflow: 'Flux de travail',
  dash_orderEntry_title: 'Saisie',
  dash_orderEntry_desc: 'Enregistrez un nouveau dossier d’anatomie pathologique. Saisissez les informations du patient et du clinicien, ajoutez les prélèvements et générez la feuille de travail.',
  dash_processing_title: 'File de traitement',
  dash_processing_desc: 'Cas en attente d’examen macroscopique et de préparation des blocs et lames. Sélectionnez un cas pour enregistrer les blocs et lames pour chaque prélèvement.',
  dash_result_title: 'File de résultats',
  dash_result_desc: 'Cas avec lames prêtes pour l’examen microscopique et la rédaction du rapport. Signez les cas terminés ici.',
  dash_query_title: 'Recherche',
  dash_query_desc: 'Recherchez un dossier par identifiant de cas ou identifiant patient afin de consulter son état, ses matériels et ses rapports.',
  dash_systemDesc: 'Un système léger de gestion de flux de travail pour les laboratoires d’anatomie pathologique. Suivez les dossiers de l’enregistrement initial jusqu’à l’examen macroscopique, la préparation des lames, l’examen microscopique et la signature finale.',
  dash_loggedInAs: 'Connecté en tant que',
  pq_title: 'File de traitement',
  pq_searchPlaceholder: 'Rechercher un identifiant de cas, un identifiant patient ou un nom de patient',
  pq_showAll: 'Tout afficher, y compris les cas terminés',
  pq_caseId: 'Identifiant du cas',
  pq_patient: 'Patient',
  pq_clinician: 'Clinicien',
  pq_registered: 'Enregistré',
  pq_type: 'Type',
  pq_specimens: 'Prélèvements',
  pq_noCases: 'Aucun cas dans la file',
  rq_title: 'File de résultats',
  rq_pendingResult: 'Résultat en attente',
  rq_reactivated: 'Réactivé',
  rq_status: 'Statut',
  rq_noCases: 'Aucun cas en attente de résultat',
  q_title: 'Recherche',
  q_caseId: 'Identifiant du cas',
  q_patientId: 'Identifiant patient',
  q_search: 'Rechercher',
  q_status: 'Statut',
  q_signedOut: 'Signé',
  q_inProgress: 'En cours',
  q_noResults: 'Aucun cas correspondant trouvé',
  q_error: 'La recherche a échoué. Veuillez réessayer.',
  q_searchFailed: 'La recherche a échoué. Veuillez réessayer.',
  oe_title: 'Saisie',
  oe_patient: 'Patient',
  oe_existing: 'Existant',
  oe_new: 'Nouveau',
  oe_searchPatient: 'Rechercher un patient',
  oe_searchClinician: 'Rechercher un clinicien',
  oe_clinician: 'Clinicien',
  oe_caseDetails: 'Détails du cas',
  oe_caseType: 'Type de cas',
  oe_surgicalPathology: 'Anatomopathologie chirurgicale',
  oe_cytology: 'Cytologie',
  oe_specimens: 'Prélèvements',
  oe_addSpecimen: 'Ajouter un prélèvement',
  oe_specimen: 'Prélèvement',
  oe_site: 'Site',
  oe_organ: 'Organe',
  oe_specimenType: 'Type de prélèvement',
  oe_coldIschemicTime: 'Temps d’ischémie froide (min)',
  oe_createCase: 'Créer le cas',
  oe_caseCreated: 'Cas créé :',
  oe_worksheetPdf: 'PDF de la feuille de travail',
  oe_sex: 'Sexe',
  oe_dob: 'Date de naissance',
  oe_firstName: 'Prénom',
  oe_lastName: 'Nom',
  oe_dateOfBirth: 'Date de naissance',
  oe_sexMale: 'Masculin',
  oe_sexFemale: 'Féminin',
  oe_sexOther: 'Autre',
  oe_sexUnknown: 'Inconnu',
  specimenType_biopsy: 'Biopsie',
  specimenType_excision: 'Exérèse',
  specimenType_resection: 'Résection',
  specimenType_cytology: 'Cytologie',
  specimenType_coreNeedleBiopsy: 'Biopsie à l’aiguille tru-cut',
  specimenType_fineNeedleAspiration: 'Cytoponction à l’aiguille fine',
  specimenType_curettage: 'Curetage',
  specimenType_polypectomy: 'Polypectomie',
  specimenType_amputation: 'Amputation',
  specimenType_boneMarrowBiopsy: 'Biopsie de moelle osseuse',
  slideType_he: 'H&E',
  slideType_unstained: 'Non colorée',
  slideType_ihc: 'IHC',
  slideType_specialStain: 'Coloration spéciale',
  slideType_other: 'Autre',
  pc_referenceStrips: 'PDF des bandelettes de référence',
  pc_referenceStripsPdf: 'PDF des bandelettes de référence',
  pc_save: 'Enregistrer',
  pc_saveAndExit: 'Enregistrer et quitter',
  pc_saved: 'Cas enregistré',
  pc_caseSaved: 'Cas enregistré',
  pc_saveFailed: 'Échec de l’enregistrement du cas',
  pc_blockId: 'ID du bloc',
  pc_slides: 'Lames',
  pc_addSlides: 'Ajouter des lames',
  pc_addSlidesHeader: 'Ajouter des lames',
  pc_deleteBlock: 'Supprimer le bloc et toutes ses lames',
  pc_deleteBlockTooltip: 'Supprimer le bloc et toutes ses lames',
  common_delete: 'Supprimer',
  pc_numBlocks: 'Nb de blocs',
  pc_numSlides: 'Nb de lames',
  pc_addBlock: 'Ajouter un bloc',
  pc_addBlocks: 'Ajouter des blocs',
  pc_addSlide: 'Ajouter une lame',
  pc_addSlidesBtn: 'Ajouter des lames',
  pc_noSlides: 'aucune',
  pc_none: 'aucune',
  pc_noSlidesYet: 'Aucune lame pour le moment',
  pc_slideType: 'Type de lame',
  site_gi: 'Gastro-intestinal (GI)',
  site_hepatobiliary: 'Hépatobiliaire et pancréas',
  site_breast: 'Sein',
  site_gynecologic: 'Gynécologique',
  site_urologic: 'Urologique (GU)',
  site_headNeck: 'Tête et cou',
  site_respiratory: 'Respiratoire (poumon et plèvre)',
  site_skin: 'Peau',
  site_lymph: 'Ganglion lymphatique / hématolymphoïde',
  site_boneSoft: 'Os et tissus mous',
  site_cns: 'Système nerveux central (SNC)',
  site_placenta: 'Placenta / produits de conception',
  site_fna: 'Cytoponction à l’aiguille fine (FNA)',
  site_csf: 'LCR (liquide céphalorachidien)',
  organ_liver: 'Foie',
  organ_gallbladder: 'Vésicule biliaire',
  organ_bileDuct: 'Canal biliaire',
  organ_pancreas: 'Pancréas',
  organ_breast: 'Sein',
  organ_synovialFluid: 'Liquide synovial',
  organ_csfSite: 'LCR (liquide céphalorachidien)',
  pc_clinicalHistory: 'Antécédents cliniques',
  pc_grossDescription: 'Description macroscopique',
  pc_openResults: 'Ouvrir les résultats',
  pc_materials: 'Matériels',
  pc_noSpecimens: 'Aucun prélèvement trouvé pour ce cas.',
  rc_processing: 'Traitement',
  rc_finalDiagnosis: 'Diagnostic final',
  rc_comment: 'Commentaire',
  rc_microscopicDescription: 'Description microscopique',
  rc_grossDescription: 'Description macroscopique',
  rc_clinicalHistory: 'Antécédents cliniques',
  rc_capTemplate: 'Modèle CAP (facultatif)',
  rc_reportingTemplate: 'Modèle de compte rendu',
  rc_grossTemplate: 'Modèle macroscopique',
  rc_microscopicContent: 'Description microscopique',
  rc_saveDraft: 'Enregistrer le brouillon',
  rc_saveAndExit: 'Enregistrer et quitter',
  rc_exit: 'Quitter',
  rc_signOut: 'Signer',
  rc_reactivate: 'Réactiver',
  rc_signedOut: 'Signé',
  rc_draftSaved: 'Brouillon enregistré',
  rc_historySaved: 'Antécédents cliniques enregistrés',
  rc_clinicalHistorySaved: 'Antécédents cliniques enregistrés',
  rc_report: 'Rapport',
  rc_history: 'Historique',
  rc_materials: 'Matériels',
  rc_reportPdf: 'PDF du rapport',
  rc_amendedPdf: 'PDF amendé',
  rc_confirmSignOut: 'Confirmer la signature',
  rc_confirmSignOutMsg: 'Cette action est définitive. Le rapport deviendra immuable après signature.',
  rc_confirmReactivate: 'Confirmer la réactivation',
  rc_confirmReactivateMsg: 'Cela réactivera le dossier pour amendement. Êtes-vous sûr ?',
  rc_version: 'Version',
  rc_pathologist: 'Pathologiste',
  rc_date: 'Date',
  rc_signedOutStatus: 'Signé',
  rc_inProgress: 'En cours',
  rc_saveHistory: 'Enregistrer les antécédents',
  rc_signedOutAlert: 'Ce dossier est signé. Utilisez Réactiver pour créer une révision ou un addendum.',
  rc_viewReportPdf: 'Voir le PDF du rapport',
  rc_capTemplatePlaceholder: 'Sélectionnez un modèle ci-dessus puis renseignez les champs',
  rc_dob: 'Date de naissance',
  rc_sex: 'Sexe',
  rc_resultEntry: 'Saisie du résultat',
  rc_reportHistory: 'Historique du rapport',
  rc_reactivateCase: 'Réactiver le cas',
  rc_reactivateMsg: 'La réactivation créera un nouveau brouillon de rapport. Les rapports précédents restent immuables.',
  rc_revise: 'Réviser',
  rc_revision: 'Révision',
  rc_addend: 'Addendum',
  rc_none: 'Aucun',
  rc_final: 'Final',
  rc_draft: 'Brouillon',
  rc_prelim: 'Préliminaire',
  rc_signedOutSuccess: 'Rapport signé avec succès',
  rc_reactivatedSuccess: 'Cas réactivé. Un nouveau brouillon a été créé.',
  rc_signPrelim: 'Signer le préliminaire',
  rc_confirmSignPrelim: 'Confirmer la signature préliminaire',
  rc_confirmSignPrelimMsg: 'Cela générera un PDF de rapport préliminaire. Le cas restera actif pour d’autres modifications.',
  rc_signedPrelimSuccess: 'Rapport préliminaire généré. Le cas reste actif.',
  rc_viewPrelimPdf: 'Voir le PDF préliminaire',
  rc_openProcessing: 'Ouvrir le traitement',
  rc_reactivateExplanation: 'Explication (obligatoire)',
  rc_reactivateExplanationPlaceholder: 'Indiquez le motif de la réactivation ou de l’addendum...',
  rc_templateLoading: 'Chargement du modèle...',
  rc_templateUnavailable: 'Modèle indisponible. Vous pouvez continuer à modifier directement le texte généré.',
  nav_unsavedTitle: 'Modifications non enregistrées',
  nav_unsavedChanges: 'Vous avez des modifications non enregistrées. Voulez-vous vraiment quitter cette page ?',
  nav_leave: 'Quitter',
  nav_stay: 'Rester',

  // Configuration — Template Manager
  nav_config: 'Configuration',
  cfg_title: 'Gestionnaire de modèles',
  cfg_new: 'Nouveau modèle',
  cfg_save: 'Enregistrer',
  cfg_saving: 'Enregistrement...',
  cfg_saved: 'Modèle enregistré',
  cfg_saveFailed: 'Échec de l\'enregistrement du modèle',
  cfg_created: 'Modèle créé',
  cfg_createFailed: 'Échec de la création du modèle',
  cfg_clone: 'Cloner le modèle',
  cfg_coreTab: 'Principal (EN)',
  cfg_filterPlaceholder: 'Filtrer les modèles...',
  cfg_noTemplates: 'Aucun modèle trouvé',
  cfg_invalidJson: 'JSON invalide',
  cfg_preview: 'Aperçu',
  cfg_selectTemplate: 'Sélectionnez un modèle à modifier',
  cfg_kind: 'Type',
  cfg_family: 'Famille',
  cfg_templateKey: 'Clé du modèle',
  cfg_templateKeyHint: 'ex. breast.histology/breast/reporting/my_template',
  cfg_blank: 'Modèle vierge',
  cfg_cloneExisting: 'Cloner un modèle existant',
  cfg_cloneSource: 'Cloner depuis',
  cfg_step1Setup: 'Configuration',
  cfg_step2Edit: 'Modifier le JSON',
  cfg_create: 'Créer',
  cfg_gross: 'Macroscopique',
  cfg_reporting: 'Compte rendu',
  cfg_directory: 'Répertoire',
  cfg_filename: 'Nom du fichier',
  cfg_tabTemplates: 'Gestionnaire de modèles',
  cfg_tabReports: 'Gestionnaire de rapports',
  rpt_title: 'Gestionnaire de rapports',
  rpt_new: 'Nouveau modèle de rapport',
  rpt_name: 'Nom du modèle',
  rpt_type: 'Type',
  rpt_text: 'Texte du rapport',
  rpt_active: 'Actif',
  rpt_save: 'Enregistrer',
  rpt_saved: 'Enregistré',
  rpt_saveFailed: 'Échec de l\'enregistrement',
  rpt_delete: 'Supprimer',
  rpt_deleteConfirm: 'Supprimer ce modèle de rapport?',
  rpt_deleted: 'Supprimé',
  rpt_deleteFailed: 'Échec de la suppression',
  rpt_createFailed: 'Échec de la création',
  rpt_noTemplates: 'Aucun modèle de rapport',
  rpt_selectTemplate: 'Sélectionnez un modèle de rapport à modifier',
  rpt_final: 'Final',
  rpt_preliminary: 'Préliminaire',
  rpt_addendum: 'Addendum',
  rpt_revision: 'Révision',
};

const ar: Record<keyof typeof en, string> = {
  ...en,
  cases: 'حالات',
  results: 'نتائج',
  nav_home: 'الرئيسية',
  nav_orderEntry: 'إدخال الطلب',
  nav_processing: 'المعالجة',
  nav_result: 'النتائج',
  nav_query: 'الاستعلام',
  nav_logout: 'تسجيل الخروج',
  login_findEmployee: 'العثور على موظف',
  login_newEmployee: 'موظف جديد',
  login_searchPlaceholder: 'ابحث بالاسم أو اسم المستخدم',
  login_noEmployeesFound: 'لم يتم العثور على موظفين. جرّب إنشاء موظف جديد.',
  login_firstName: 'الاسم الأول',
  login_lastName: 'اسم العائلة',
  login_username: 'اسم المستخدم',
  login_role: 'الدور',
  role_pathologist: 'اختصاصي علم الأمراض',
  role_technologist: 'أخصائي المختبر',
  login_createAndLogin: 'إنشاء وتسجيل الدخول',
  login_allFieldsRequired: 'جميع الحقول مطلوبة للموظف الجديد',
  login_failed: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
  login_defaultLanguage: 'اللغة الافتراضية',
  input_keyboardLayoutHint: 'لإدخال نص عربي أو أردي، بدّل تخطيط لوحة المفاتيح. تغيير لغة التطبيق لا يغيّر أبجدية لوحة المفاتيح.',
  appFull: 'نظام معلومات مختبر علم الأمراض التشريحي',
  dash_workflow: 'سير العمل',
  dash_orderEntry_title: 'إدخال الطلب',
  dash_orderEntry_desc: 'سجّل حالة باثولوجيا جديدة. أدخل بيانات المريض والطبيب، وأضف العينات، ثم أنشئ ورقة العمل.',
  dash_processing_title: 'قائمة المعالجة',
  dash_processing_desc: 'الحالات التي تنتظر الفحص العياني وتحضير الكتل والشرائح. اختر حالة لتسجيل الكتل والشرائح لكل عينة.',
  dash_result_title: 'قائمة النتائج',
  dash_result_desc: 'الحالات التي أصبحت شرائحها جاهزة للفحص المجهري وإعداد التقرير. وقّع الحالات المكتملة من هنا.',
  dash_query_title: 'الاستعلام',
  dash_query_desc: 'ابحث عن أي حالة بواسطة رقم الحالة أو رقم المريض لمراجعة حالتها الحالية والمواد والتقارير.',
  dash_systemDesc: 'نظام خفيف لإدارة سير العمل في مختبرات علم الأمراض التشريحي. تتبّع الحالات من التسجيل الأولي مرورًا بالفحص العياني وتحضير الشرائح والفحص المجهري وحتى الاعتماد النهائي.',
  dash_loggedInAs: 'تم تسجيل الدخول باسم',
  pq_title: 'قائمة المعالجة',
  pq_searchPlaceholder: 'ابحث برقم الحالة أو رقم المريض أو اسم المريض',
  pq_showAll: 'إظهار الكل، بما في ذلك المكتمل',
  pq_caseId: 'رقم الحالة',
  pq_patient: 'المريض',
  pq_clinician: 'الطبيب',
  pq_registered: 'تاريخ التسجيل',
  pq_type: 'النوع',
  pq_specimens: 'العينات',
  pq_noCases: 'لا توجد حالات في القائمة',
  rq_title: 'قائمة النتائج',
  rq_pendingResult: 'نتيجة معلقة',
  rq_reactivated: 'أعيد تفعيلها',
  rq_status: 'الحالة',
  rq_noCases: 'لا توجد حالات بانتظار النتيجة',
  q_title: 'الاستعلام',
  q_caseId: 'رقم الحالة',
  q_patientId: 'رقم المريض',
  q_search: 'بحث',
  q_status: 'الحالة',
  q_signedOut: 'موقّع',
  q_inProgress: 'قيد العمل',
  q_noResults: 'لم يتم العثور على حالات مطابقة',
  q_error: 'فشل البحث. يرجى المحاولة مرة أخرى.',
  q_searchFailed: 'فشل البحث. يرجى المحاولة مرة أخرى.',
  oe_title: 'إدخال الطلب',
  oe_patient: 'المريض',
  oe_existing: 'موجود',
  oe_new: 'جديد',
  oe_searchPatient: 'ابحث عن مريض',
  oe_searchClinician: 'ابحث عن طبيب',
  oe_clinician: 'الطبيب',
  oe_caseDetails: 'تفاصيل الحالة',
  oe_caseType: 'نوع الحالة',
  oe_surgicalPathology: 'علم الأمراض الجراحي',
  oe_cytology: 'علم الخلايا',
  oe_specimens: 'العينات',
  oe_addSpecimen: 'إضافة عينة',
  oe_specimen: 'عينة',
  oe_site: 'الموضع',
  oe_organ: 'العضو',
  oe_specimenType: 'نوع العينة',
  oe_coldIschemicTime: 'زمن الإقفار البارد (دقيقة)',
  oe_createCase: 'إنشاء الحالة',
  oe_caseCreated: 'تم إنشاء الحالة:',
  oe_worksheetPdf: 'PDF ورقة العمل',
  oe_sex: 'الجنس',
  oe_dob: 'تاريخ الميلاد',
  oe_firstName: 'الاسم الأول',
  oe_lastName: 'اسم العائلة',
  oe_dateOfBirth: 'تاريخ الميلاد',
  oe_sexMale: 'ذكر',
  oe_sexFemale: 'أنثى',
  oe_sexOther: 'آخر',
  oe_sexUnknown: 'غير معروف',
  specimenType_biopsy: 'خزعة',
  specimenType_excision: 'استئصال',
  specimenType_resection: 'قطع جراحي',
  specimenType_cytology: 'علم الخلايا',
  specimenType_coreNeedleBiopsy: 'خزعة بإبرة غليظة',
  specimenType_fineNeedleAspiration: 'شفط بإبرة دقيقة',
  specimenType_curettage: 'كحت',
  specimenType_polypectomy: 'استئصال سليلة',
  specimenType_amputation: 'بتر',
  specimenType_boneMarrowBiopsy: 'خزعة نخاع العظم',
  slideType_he: 'H&E',
  slideType_unstained: 'غير مصبوغة',
  slideType_ihc: 'IHC',
  slideType_specialStain: 'صبغة خاصة',
  slideType_other: 'أخرى',
  pc_referenceStrips: 'PDF شرائط المرجع',
  pc_referenceStripsPdf: 'PDF شرائط المرجع',
  pc_save: 'حفظ',
  pc_saveAndExit: 'حفظ والخروج',
  pc_saved: 'تم حفظ الحالة',
  pc_caseSaved: 'تم حفظ الحالة',
  pc_saveFailed: 'فشل حفظ الحالة',
  pc_blockId: 'معرّف البلوك',
  pc_slides: 'الشرائح',
  pc_addSlides: 'إضافة شرائح',
  pc_addSlidesHeader: 'إضافة شرائح',
  pc_deleteBlock: 'حذف البلوك وجميع شرائحه',
  pc_deleteBlockTooltip: 'حذف البلوك وجميع شرائحه',
  common_delete: 'حذف',
  pc_numBlocks: 'عدد البلوكات',
  pc_numSlides: 'عدد الشرائح',
  pc_addBlock: 'إضافة بلوك',
  pc_addBlocks: 'إضافة بلوكات',
  pc_addSlide: 'إضافة شريحة',
  pc_addSlidesBtn: 'إضافة شرائح',
  pc_noSlides: 'لا توجد',
  pc_none: 'لا توجد',
  pc_noSlidesYet: 'لا توجد شرائح بعد',
  pc_slideType: 'نوع الشريحة',
  site_gi: 'الجهاز الهضمي (GI)',
  site_hepatobiliary: 'الكبد والجهاز الصفراوي والبنكرياس',
  site_breast: 'الثدي',
  site_gynecologic: 'أمراض النساء',
  site_urologic: 'المسالك البولية (GU)',
  site_headNeck: 'الرأس والعنق',
  site_respiratory: 'الجهاز التنفسي (الرئة والجنب)',
  site_skin: 'الجلد',
  site_lymph: 'العقد اللمفاوية / الدموي اللمفاوي',
  site_boneSoft: 'العظام والأنسجة الرخوة',
  site_cns: 'الجهاز العصبي المركزي (CNS)',
  site_placenta: 'المشيمة / نواتج الحمل',
  site_fna: 'شفط بإبرة دقيقة (FNA)',
  site_csf: 'السائل الدماغي النخاعي (CSF)',
  organ_liver: 'الكبد',
  organ_gallbladder: 'المرارة',
  organ_bileDuct: 'القناة الصفراوية',
  organ_pancreas: 'البنكرياس',
  organ_breast: 'الثدي',
  organ_synovialFluid: 'السائل الزليلي',
  organ_csfSite: 'السائل الدماغي النخاعي (CSF)',
  pc_clinicalHistory: 'التاريخ السريري',
  pc_grossDescription: 'الوصف العياني',
  pc_openResults: 'فتح النتائج',
  pc_materials: 'المواد',
  pc_noSpecimens: 'لم يتم العثور على عينات لهذه الحالة.',
  rc_processing: 'المعالجة',
  rc_finalDiagnosis: 'التشخيص النهائي',
  rc_comment: 'تعليق',
  rc_microscopicDescription: 'الوصف المجهري',
  rc_grossDescription: 'الوصف العياني',
  rc_clinicalHistory: 'التاريخ السريري',
  rc_capTemplate: 'قالب CAP اختياري',
  rc_reportingTemplate: 'قالب التقرير',
  rc_grossTemplate: 'قالب الوصف العياني',
  rc_microscopicContent: 'الوصف المجهري',
  rc_saveDraft: 'حفظ المسودة',
  rc_saveAndExit: 'حفظ والخروج',
  rc_exit: 'خروج',
  rc_signOut: 'اعتماد نهائي',
  rc_reactivate: 'إعادة التفعيل',
  rc_signedOut: 'تم الاعتماد',
  rc_draftSaved: 'تم حفظ المسودة',
  rc_historySaved: 'تم حفظ التاريخ السريري',
  rc_clinicalHistorySaved: 'تم حفظ التاريخ السريري',
  rc_report: 'التقرير',
  rc_history: 'السجل',
  rc_materials: 'المواد',
  rc_reportPdf: 'ملف PDF للتقرير',
  rc_amendedPdf: 'ملف PDF المعدّل',
  rc_confirmSignOut: 'تأكيد الاعتماد',
  rc_confirmSignOutMsg: 'هذا الإجراء نهائي. سيصبح التقرير غير قابل للتعديل بعد الاعتماد.',
  rc_confirmReactivate: 'تأكيد إعادة التفعيل',
  rc_confirmReactivateMsg: 'سيؤدي هذا إلى إعادة تفعيل الحالة للتعديل. هل أنت متأكد؟',
  rc_version: 'الإصدار',
  rc_pathologist: 'اختصاصي علم الأمراض',
  rc_date: 'التاريخ',
  rc_signedOutStatus: 'تم الاعتماد',
  rc_inProgress: 'قيد العمل',
  rc_saveHistory: 'حفظ التاريخ',
  rc_signedOutAlert: 'هذه الحالة معتمدة. استخدم إعادة التفعيل لإنشاء مراجعة أو إضافة.',
  rc_viewReportPdf: 'عرض ملف PDF للتقرير',
  rc_capTemplatePlaceholder: 'اختر قالبًا أعلاه ثم املأ الحقول',
  rc_dob: 'تاريخ الميلاد',
  rc_sex: 'الجنس',
  rc_resultEntry: 'إدخال النتيجة',
  rc_reportHistory: 'سجل التقارير',
  rc_reactivateCase: 'إعادة تفعيل الحالة',
  rc_reactivateMsg: 'ستنشئ إعادة التفعيل مسودة تقرير جديدة. تبقى التقارير السابقة غير قابلة للتعديل.',
  rc_revise: 'مراجعة',
  rc_revision: 'مراجعة',
  rc_addend: 'إضافة',
  rc_none: 'لا شيء',
  rc_final: 'نهائي',
  rc_draft: 'مسودة',
  rc_prelim: 'أولي',
  rc_signedOutSuccess: 'تم اعتماد التقرير بنجاح',
  rc_reactivatedSuccess: 'أعيد تفعيل الحالة. تم إنشاء مسودة جديدة.',
  rc_signPrelim: 'اعتماد أولي',
  rc_confirmSignPrelim: 'تأكيد الاعتماد الأولي',
  rc_confirmSignPrelimMsg: 'سيؤدي ذلك إلى إنشاء ملف PDF لتقرير أولي. ستظل الحالة نشطة لمزيد من التعديلات.',
  rc_signedPrelimSuccess: 'تم إنشاء التقرير الأولي. ما زالت الحالة نشطة.',
  rc_viewPrelimPdf: 'عرض ملف PDF الأولي',
  rc_openProcessing: 'فتح المعالجة',
  rc_reactivateExplanation: 'التوضيح مطلوب',
  rc_reactivateExplanationPlaceholder: 'اذكر سبب إعادة التفعيل أو الإضافة...',
  rc_templateLoading: 'جارٍ تحميل القالب...',
  rc_templateUnavailable: 'القالب غير متاح. يمكنك متابعة تعديل النص المُنشأ مباشرة.',
  nav_unsavedTitle: 'تغييرات غير محفوظة',
  nav_unsavedChanges: 'لديك تغييرات غير محفوظة. هل أنت متأكد من مغادرة الصفحة؟',
  nav_leave: 'مغادرة',
  nav_stay: 'البقاء',

  // Configuration — Template Manager
  nav_config: 'الإعدادات',
  cfg_title: 'مدير القوالب',
  cfg_new: 'قالب جديد',
  cfg_save: 'حفظ',
  cfg_saving: 'جارٍ الحفظ...',
  cfg_saved: 'تم حفظ القالب',
  cfg_saveFailed: 'فشل حفظ القالب',
  cfg_created: 'تم إنشاء القالب',
  cfg_createFailed: 'فشل إنشاء القالب',
  cfg_clone: 'نسخ القالب',
  cfg_coreTab: 'الأساسي (EN)',
  cfg_filterPlaceholder: 'تصفية القوالب...',
  cfg_noTemplates: 'لم يتم العثور على قوالب',
  cfg_invalidJson: 'JSON غير صالح',
  cfg_preview: 'معاينة',
  cfg_selectTemplate: 'اختر قالبًا للتحرير',
  cfg_kind: 'النوع',
  cfg_family: 'المجموعة',
  cfg_templateKey: 'مفتاح القالب',
  cfg_templateKeyHint: 'مثال: breast.histology/breast/reporting/my_template',
  cfg_blank: 'قالب فارغ',
  cfg_cloneExisting: 'نسخ قالب موجود',
  cfg_cloneSource: 'نسخ من',
  cfg_step1Setup: 'إعداد',
  cfg_step2Edit: 'تحرير JSON',
  cfg_create: 'إنشاء',
  cfg_gross: 'عياني',
  cfg_reporting: 'تقرير',
  cfg_directory: 'المجلد',
  cfg_filename: 'اسم الملف',
  cfg_tabTemplates: 'مدير القوالب',
  cfg_tabReports: 'مدير التقارير',
  rpt_title: 'مدير التقارير',
  rpt_new: 'قالب تقرير جديد',
  rpt_name: 'اسم القالب',
  rpt_type: 'النوع',
  rpt_text: 'نص التقرير',
  rpt_active: 'نشط',
  rpt_save: 'حفظ',
  rpt_saved: 'تم الحفظ',
  rpt_saveFailed: 'فشل الحفظ',
  rpt_delete: 'حذف',
  rpt_deleteConfirm: 'هل تريد حذف قالب التقرير هذا؟',
  rpt_deleted: 'تم الحذف',
  rpt_deleteFailed: 'فشل الحذف',
  rpt_createFailed: 'فشل الإنشاء',
  rpt_noTemplates: 'لا توجد قوالب تقارير',
  rpt_selectTemplate: 'اختر قالب تقرير للتعديل',
  rpt_final: 'نهائي',
  rpt_preliminary: 'أولي',
  rpt_addendum: 'ملحق',
  rpt_revision: 'مراجعة',
};

const ur: Record<keyof typeof en, string> = {
  ...en,
  cases: 'کیسز',
  results: 'نتائج',
  nav_home: 'ہوم',
  nav_orderEntry: 'آرڈر اندراج',
  nav_processing: 'پروسیسنگ',
  nav_result: 'نتیجہ',
  nav_query: 'تلاش',
  nav_logout: 'لاگ آؤٹ',
  login_findEmployee: 'ملازم تلاش کریں',
  login_newEmployee: 'نیا ملازم',
  login_searchPlaceholder: 'نام یا صارف نام سے تلاش کریں',
  login_noEmployeesFound: 'کوئی ملازم نہیں ملا۔ نیا ملازم بنانے کی کوشش کریں۔',
  login_firstName: 'پہلا نام',
  login_lastName: 'آخری نام',
  login_username: 'صارف نام',
  login_role: 'کردار',
  role_pathologist: 'پیتھالوجسٹ',
  role_technologist: 'لیب ٹیکنالوجسٹ',
  login_createAndLogin: 'بنائیں اور لاگ اِن کریں',
  login_allFieldsRequired: 'نئے ملازم کے لیے تمام خانے ضروری ہیں',
  login_failed: 'لاگ اِن ناکام ہو گیا۔ دوبارہ کوشش کریں۔',
  login_defaultLanguage: 'ڈیفالٹ زبان',
  input_keyboardLayoutHint: 'عربی یا اردو متن لکھنے کے لیے اپنی کی بورڈ لے آؤٹ تبدیل کریں۔ ایپ کی زبان بدلنے سے کی بورڈ کا حروف تہجی نہیں بدلتا۔',
  appFull: 'ایناتومک پیتھالوجی لیبارٹری انفارمیشن سسٹم',
  dash_workflow: 'ورک فلو',
  dash_orderEntry_title: 'آرڈر اندراج',
  dash_orderEntry_desc: 'نیا پیتھالوجی کیس درج کریں۔ مریض اور معالج کی تفصیل درج کریں، نمونے شامل کریں، اور ورک شیٹ بنائیں۔',
  dash_processing_title: 'پروسیسنگ قطار',
  dash_processing_desc: 'وہ کیسز جو گراسنگ اور بلاک و سلائیڈ تیاری کے منتظر ہیں۔ ہر نمونے کے لیے بلاکس اور سلائیڈز درج کرنے کو کیس منتخب کریں۔',
  dash_result_title: 'نتیجہ قطار',
  dash_result_desc: 'وہ کیسز جن کی سلائیڈز تیار ہیں اور مائیکروسکوپک معائنہ و رپورٹنگ کے لیے تیار ہیں۔ مکمل کیسز یہاں سائن آؤٹ کریں۔',
  dash_query_title: 'تلاش',
  dash_query_desc: 'کیس آئی ڈی یا مریض آئی ڈی کے ذریعے کسی بھی کیس کو تلاش کریں تاکہ اس کی موجودہ حالت، مواد، اور رپورٹس دیکھی جا سکیں۔',
  dash_systemDesc: 'اناٹومک پیتھالوجی لیبارٹریوں کے لیے ہلکا پھلکا ورک فلو مینجمنٹ سسٹم۔ ابتدائی رجسٹریشن سے گراسنگ، سلائیڈ تیاری، مائیکروسکوپک معائنہ، اور حتمی سائن آؤٹ تک کیسز کو ٹریک کریں۔',
  dash_loggedInAs: 'لاگ اِن بطور',
  pq_title: 'پروسیسنگ قطار',
  pq_searchPlaceholder: 'کیس آئی ڈی، مریض آئی ڈی، یا مریض کے نام سے تلاش کریں',
  pq_showAll: 'سب دکھائیں، مکمل شدہ بھی',
  pq_caseId: 'کیس آئی ڈی',
  pq_patient: 'مریض',
  pq_clinician: 'معالج',
  pq_registered: 'رجسٹرڈ',
  pq_type: 'قسم',
  pq_specimens: 'نمونے',
  pq_noCases: 'قطار میں کوئی کیس نہیں',
  rq_title: 'نتیجہ قطار',
  rq_pendingResult: 'نتیجہ زیر التوا',
  rq_reactivated: 'دوبارہ فعال',
  rq_status: 'حالت',
  rq_noCases: 'نتیجے کے انتظار میں کوئی کیس نہیں',
  q_title: 'تلاش',
  q_caseId: 'کیس آئی ڈی',
  q_patientId: 'مریض آئی ڈی',
  q_search: 'تلاش',
  q_status: 'حالت',
  q_signedOut: 'سائن آؤٹ',
  q_inProgress: 'زیر عمل',
  q_noResults: 'کوئی مماثل کیس نہیں ملا',
  q_error: 'تلاش ناکام رہی۔ دوبارہ کوشش کریں۔',
  q_searchFailed: 'تلاش ناکام رہی۔ دوبارہ کوشش کریں۔',
  oe_title: 'آرڈر اندراج',
  oe_patient: 'مریض',
  oe_existing: 'موجودہ',
  oe_new: 'نیا',
  oe_searchPatient: 'مریض تلاش کریں',
  oe_searchClinician: 'معالج تلاش کریں',
  oe_clinician: 'معالج',
  oe_caseDetails: 'کیس کی تفصیلات',
  oe_caseType: 'کیس کی قسم',
  oe_surgicalPathology: 'سرجیکل پیتھالوجی',
  oe_cytology: 'سائٹولوجی',
  oe_specimens: 'نمونے',
  oe_addSpecimen: 'نمونہ شامل کریں',
  oe_specimen: 'نمونہ',
  oe_site: 'مقام',
  oe_organ: 'عضو',
  oe_specimenType: 'نمونے کی قسم',
  oe_coldIschemicTime: 'کولڈ اسکیمک ٹائم (منٹ)',
  oe_createCase: 'کیس بنائیں',
  oe_caseCreated: 'کیس بنایا گیا:',
  oe_worksheetPdf: 'ورک شیٹ PDF',
  oe_sex: 'جنس',
  oe_dob: 'تاریخ پیدائش',
  oe_firstName: 'پہلا نام',
  oe_lastName: 'آخری نام',
  oe_dateOfBirth: 'تاریخ پیدائش',
  oe_sexMale: 'مرد',
  oe_sexFemale: 'عورت',
  oe_sexOther: 'دیگر',
  oe_sexUnknown: 'نامعلوم',
  specimenType_biopsy: 'بایوپسی',
  specimenType_excision: 'اخراج',
  specimenType_resection: 'ریسیکشن',
  specimenType_cytology: 'سائٹولوجی',
  specimenType_coreNeedleBiopsy: 'کور نیڈل بایوپسی',
  specimenType_fineNeedleAspiration: 'فائن نیڈل اسپائریشن',
  specimenType_curettage: 'کیوریٹیج',
  specimenType_polypectomy: 'پولیپیکٹومی',
  specimenType_amputation: 'امپیوٹیشن',
  specimenType_boneMarrowBiopsy: 'بون میرو بایوپسی',
  slideType_he: 'H&E',
  slideType_unstained: 'بغیر رنگ کی',
  slideType_ihc: 'IHC',
  slideType_specialStain: 'خصوصی رنگ',
  slideType_other: 'دیگر',
  pc_referenceStrips: 'حوالہ اسٹرپس PDF',
  pc_referenceStripsPdf: 'حوالہ اسٹرپس PDF',
  pc_save: 'محفوظ کریں',
  pc_saveAndExit: 'محفوظ کر کے باہر جائیں',
  pc_saved: 'کیس محفوظ ہو گیا',
  pc_caseSaved: 'کیس محفوظ ہو گیا',
  pc_saveFailed: 'کیس محفوظ کرنے میں ناکامی',
  pc_blockId: 'بلاک آئی ڈی',
  pc_slides: 'سلائیڈز',
  pc_addSlides: 'سلائیڈز شامل کریں',
  pc_addSlidesHeader: 'سلائیڈز شامل کریں',
  pc_deleteBlock: 'بلاک اور اس کی تمام سلائیڈز حذف کریں',
  pc_deleteBlockTooltip: 'بلاک اور اس کی تمام سلائیڈز حذف کریں',
  common_delete: 'حذف کریں',
  pc_numBlocks: 'بلاکس کی تعداد',
  pc_numSlides: 'سلائیڈز کی تعداد',
  pc_addBlock: 'بلاک شامل کریں',
  pc_addBlocks: 'بلاکس شامل کریں',
  pc_addSlide: 'سلائیڈ شامل کریں',
  pc_addSlidesBtn: 'سلائیڈز شامل کریں',
  pc_noSlides: 'کوئی نہیں',
  pc_none: 'کوئی نہیں',
  pc_noSlidesYet: 'ابھی کوئی سلائیڈ نہیں',
  pc_slideType: 'سلائیڈ کی قسم',
  site_gi: 'معدی و آنتوں کا نظام (GI)',
  site_hepatobiliary: 'جگر، صفراوی نظام اور لبلبہ',
  site_breast: 'چھاتی',
  site_gynecologic: 'امراضِ نسواں',
  site_urologic: 'نظام بول و تناسل (GU)',
  site_headNeck: 'سر اور گردن',
  site_respiratory: 'نظام تنفس (پھیپھڑے اور پلورا)',
  site_skin: 'جلد',
  site_lymph: 'لمفی غدود / ہیماتولمفائیڈ',
  site_boneSoft: 'ہڈی اور نرم بافت',
  site_cns: 'مرکزی اعصابی نظام (CNS)',
  site_placenta: 'نال / باقیاتِ حمل',
  site_fna: 'فائن نیڈل اسپائریشن (FNA)',
  site_csf: 'سی ایس ایف (دماغی نخاعی سیال)',
  organ_liver: 'جگر',
  organ_gallbladder: 'پتا',
  organ_bileDuct: 'صفراوی نالی',
  organ_pancreas: 'لبلبہ',
  organ_breast: 'چھاتی',
  organ_synovialFluid: 'زلالی سیال',
  organ_csfSite: 'سی ایس ایف (دماغی نخاعی سیال)',
  pc_clinicalHistory: 'کلینیکل ہسٹری',
  pc_grossDescription: 'گروس تفصیل',
  pc_openResults: 'نتائج کھولیں',
  pc_materials: 'مواد',
  pc_noSpecimens: 'اس کیس کے لیے کوئی نمونہ نہیں ملا۔',
  rc_processing: 'پروسیسنگ',
  rc_finalDiagnosis: 'حتمی تشخیص',
  rc_comment: 'تبصرہ',
  rc_microscopicDescription: 'مائیکروسکوپک تفصیل',
  rc_grossDescription: 'گروس تفصیل',
  rc_clinicalHistory: 'کلینیکل ہسٹری',
  rc_capTemplate: 'اختیاری CAP سانچہ',
  rc_reportingTemplate: 'رپورٹنگ سانچہ',
  rc_grossTemplate: 'گروس سانچہ',
  rc_microscopicContent: 'مائیکروسکوپک تفصیل',
  rc_saveDraft: 'مسودہ محفوظ کریں',
  rc_saveAndExit: 'محفوظ کر کے باہر جائیں',
  rc_exit: 'باہر نکلیں',
  rc_signOut: 'سائن آؤٹ',
  rc_reactivate: 'دوبارہ فعال کریں',
  rc_signedOut: 'سائن آؤٹ شدہ',
  rc_draftSaved: 'مسودہ محفوظ ہو گیا',
  rc_historySaved: 'کلینیکل ہسٹری محفوظ ہو گئی',
  rc_clinicalHistorySaved: 'کلینیکل ہسٹری محفوظ ہو گئی',
  rc_report: 'رپورٹ',
  rc_history: 'ہسٹری',
  rc_materials: 'مواد',
  rc_reportPdf: 'رپورٹ PDF',
  rc_amendedPdf: 'ترمیم شدہ PDF',
  rc_confirmSignOut: 'سائن آؤٹ کی توثیق کریں',
  rc_confirmSignOutMsg: 'یہ عمل حتمی ہے۔ سائن آؤٹ کے بعد رپورٹ ناقابلِ ترمیم ہو جائے گی۔',
  rc_confirmReactivate: 'دوبارہ فعالی کی توثیق کریں',
  rc_confirmReactivateMsg: 'اس سے کیس ترمیم کے لیے دوبارہ فعال ہو جائے گا۔ کیا آپ کو یقین ہے؟',
  rc_version: 'ورژن',
  rc_pathologist: 'پیتھالوجسٹ',
  rc_date: 'تاریخ',
  rc_signedOutStatus: 'سائن آؤٹ شدہ',
  rc_inProgress: 'زیر عمل',
  rc_saveHistory: 'ہسٹری محفوظ کریں',
  rc_signedOutAlert: 'یہ کیس سائن آؤٹ ہو چکا ہے۔ ترمیم یا اضافہ بنانے کے لیے دوبارہ فعال کریں استعمال کریں۔',
  rc_viewReportPdf: 'رپورٹ PDF دیکھیں',
  rc_capTemplatePlaceholder: 'اوپر سے ایک سانچہ منتخب کریں، پھر خانے پُر کریں',
  rc_dob: 'تاریخ پیدائش',
  rc_sex: 'جنس',
  rc_resultEntry: 'نتیجہ اندراج',
  rc_reportHistory: 'رپورٹ ہسٹری',
  rc_reactivateCase: 'کیس دوبارہ فعال کریں',
  rc_reactivateMsg: 'دوبارہ فعال کرنے سے نئی ڈرافٹ رپورٹ بنے گی۔ سابقہ رپورٹس ناقابلِ ترمیم رہیں گی۔',
  rc_revise: 'نظرِ ثانی',
  rc_revision: 'نظرِ ثانی',
  rc_addend: 'ضمیمہ',
  rc_none: 'کوئی نہیں',
  rc_final: 'حتمی',
  rc_draft: 'مسودہ',
  rc_prelim: 'ابتدائی',
  rc_signedOutSuccess: 'رپورٹ کامیابی سے سائن آؤٹ ہو گئی',
  rc_reactivatedSuccess: 'کیس دوبارہ فعال ہو گیا۔ نئی ڈرافٹ بن گئی ہے۔',
  rc_signPrelim: 'ابتدائی سائن آؤٹ',
  rc_confirmSignPrelim: 'ابتدائی سائن آؤٹ کی توثیق کریں',
  rc_confirmSignPrelimMsg: 'اس سے ابتدائی رپورٹ PDF بنے گا۔ کیس مزید ترمیم کے لیے فعال رہے گا۔',
  rc_signedPrelimSuccess: 'ابتدائی رپورٹ بن گئی۔ کیس فعال ہے۔',
  rc_viewPrelimPdf: 'ابتدائی PDF دیکھیں',
  rc_openProcessing: 'پروسیسنگ کھولیں',
  rc_reactivateExplanation: 'وضاحت درکار ہے',
  rc_reactivateExplanationPlaceholder: 'دوبارہ فعالی یا ضمیمہ کی وجہ درج کریں...',
  rc_templateLoading: 'سانچہ لوڈ ہو رہا ہے...',
  rc_templateUnavailable: 'سانچہ دستیاب نہیں ہے۔ آپ تیار شدہ متن میں براہ راست ترمیم جاری رکھ سکتے ہیں۔',
  nav_unsavedTitle: 'غیر محفوظ تبدیلیاں',
  nav_unsavedChanges: 'آپ کی کچھ تبدیلیاں محفوظ نہیں ہوئیں۔ کیا آپ واقعی صفحہ چھوڑنا چاہتے ہیں؟',
  nav_leave: 'چھوڑ دیں',
  nav_stay: 'رہیں',

  // Configuration — Template Manager
  nav_config: 'ترتیبات',
  cfg_title: 'سانچہ مینیجر',
  cfg_new: 'نیا سانچہ',
  cfg_save: 'محفوظ کریں',
  cfg_saving: 'محفوظ ہو رہا ہے...',
  cfg_saved: 'سانچہ محفوظ ہو گیا',
  cfg_saveFailed: 'سانچہ محفوظ کرنے میں ناکامی',
  cfg_created: 'سانچہ بن گیا',
  cfg_createFailed: 'سانچہ بنانے میں ناکامی',
  cfg_clone: 'سانچہ کاپی کریں',
  cfg_coreTab: 'بنیادی (EN)',
  cfg_filterPlaceholder: 'سانچے فلٹر کریں...',
  cfg_noTemplates: 'کوئی سانچہ نہیں ملا',
  cfg_invalidJson: 'غلط JSON',
  cfg_preview: 'پیش نظارہ',
  cfg_selectTemplate: 'ترمیم کے لیے سانچہ منتخب کریں',
  cfg_kind: 'قسم',
  cfg_family: 'خاندان',
  cfg_templateKey: 'سانچہ کلید',
  cfg_templateKeyHint: 'مثال: breast.histology/breast/reporting/my_template',
  cfg_blank: 'خالی سانچہ',
  cfg_cloneExisting: 'موجودہ سانچہ کاپی کریں',
  cfg_cloneSource: 'سے کاپی کریں',
  cfg_step1Setup: 'ترتیب',
  cfg_step2Edit: 'JSON ترمیم',
  cfg_create: 'بنائیں',
  cfg_gross: 'گروس',
  cfg_reporting: 'رپورٹ',
  cfg_directory: 'ڈائریکٹری',
  cfg_filename: 'فائل کا نام',
  cfg_tabTemplates: 'ٹیمپلیٹ منیجر',
  cfg_tabReports: 'رپورٹ منیجر',
  rpt_title: 'رپورٹ منیجر',
  rpt_new: 'نئی رپورٹ ٹیمپلیٹ',
  rpt_name: 'ٹیمپلیٹ کا نام',
  rpt_type: 'قسم',
  rpt_text: 'رپورٹ متن',
  rpt_active: 'فعال',
  rpt_save: 'محفوظ کریں',
  rpt_saved: 'محفوظ ہو گیا',
  rpt_saveFailed: 'محفوظ کرنے میں ناکامی',
  rpt_delete: 'حذف کریں',
  rpt_deleteConfirm: 'اس رپورٹ ٹیمپلیٹ کو حذف کریں؟',
  rpt_deleted: 'حذف ہو گیا',
  rpt_deleteFailed: 'حذف کرنے میں ناکامی',
  rpt_createFailed: 'بنانے میں ناکامی',
  rpt_noTemplates: 'کوئی رپورٹ ٹیمپلیٹ نہیں',
  rpt_selectTemplate: 'ترمیم کے لیے رپورٹ ٹیمپلیٹ منتخب کریں',
  rpt_final: 'حتمی',
  rpt_preliminary: 'ابتدائی',
  rpt_addendum: 'ضمیمہ',
  rpt_revision: 'نظر ثانی',
};

// ---------------------------------------------------------------------------
// Lookup maps: English name → translation key
// ---------------------------------------------------------------------------

export const SITE_KEY_MAP: Record<string, keyof typeof en> = {
  'Gastrointestinal (GI)': 'site_gi',
  'Hepatobiliary & Pancreas': 'site_hepatobiliary',
  'Breast': 'site_breast',
  'Gynecologic': 'site_gynecologic',
  'Urologic (GU)': 'site_urologic',
  'Head & Neck': 'site_headNeck',
  'Respiratory (Lung & Pleura)': 'site_respiratory',
  'Skin': 'site_skin',
  'Lymph Node / Hematolymphoid': 'site_lymph',
  'Bone & Soft Tissue': 'site_boneSoft',
  'Central Nervous System (CNS)': 'site_cns',
  'Placenta / Products of Conception': 'site_placenta',
  'GYN Cytology (Pap smears)': 'site_gynCyto',
  'Fine Needle Aspiration (FNA)': 'site_fna',
  'Fluid Cytology (Effusions)': 'site_fluidCyto',
  'Urine Cytology': 'site_urine',
  'Respiratory Cytology': 'site_respCyto',
  'CSF (Cerebrospinal fluid)': 'site_csf',
  'Body Fluid (Non-effusion)': 'site_bodyFluid',
};

export const ORGAN_KEY_MAP: Record<string, keyof typeof en> = {
  'Esophagus': 'organ_esophagus',
  'Stomach': 'organ_stomach',
  'Duodenum': 'organ_duodenum',
  'Small bowel (jejunum/ileum)': 'organ_smallBowel',
  'Colon': 'organ_colon',
  'Rectum': 'organ_rectum',
  'Appendix': 'organ_appendix',
  'Anus': 'organ_anus',
  'Liver': 'organ_liver',
  'Gallbladder': 'organ_gallbladder',
  'Bile duct': 'organ_bileDuct',
  'Pancreas': 'organ_pancreas',
  'Breast': 'organ_breast',
  'Axillary tissue': 'organ_axillary',
  'Cervix': 'organ_cervix',
  'Endometrium': 'organ_endometrium',
  'Myometrium': 'organ_myometrium',
  'Ovary': 'organ_ovary',
  'Fallopian tube': 'organ_fallopian',
  'Vulva': 'organ_vulva',
  'Vagina': 'organ_vagina',
  'Prostate': 'organ_prostate',
  'Bladder': 'organ_bladder',
  'Kidney': 'organ_kidney',
  'Ureter': 'organ_ureter',
  'Testis': 'organ_testis',
  'Epididymis': 'organ_epididymis',
  'Penis': 'organ_penis',
  'Oral cavity': 'organ_oralCavity',
  'Tongue': 'organ_tongue',
  'Salivary gland': 'organ_salivaryGland',
  'Thyroid': 'organ_thyroid',
  'Parathyroid': 'organ_parathyroid',
  'Larynx': 'organ_larynx',
  'Pharynx': 'organ_pharynx',
  'Nasal cavity / Sinus': 'organ_nasalSinus',
  'Neck (soft tissue/unspecified)': 'organ_neckSoftTissue',
  'Lung': 'organ_lung',
  'Pleura': 'organ_pleura',
  'Bronchus': 'organ_bronchus',
  'Skin': 'organ_skin',
  'Lymph node': 'organ_lymphNode',
  'Spleen': 'organ_spleen',
  'Bone marrow': 'organ_bonemarrow',
  'Bone': 'organ_bone',
  'Soft tissue': 'organ_softTissue',
  'Brain': 'organ_brain',
  'Spinal cord': 'organ_spinalCord',
  'Meninges': 'organ_meninges',
  'Placenta': 'organ_placenta',
  'Products of conception': 'organ_poc',
  'Pleural fluid': 'organ_pleuralFluid',
  'Ascitic fluid': 'organ_asciticFluid',
  'Pericardial fluid': 'organ_pericardialFluid',
  'Sputum': 'organ_sputum',
  'Bronchial wash': 'organ_bronchialWash',
  'Bronchial brush': 'organ_bronchialBrush',
  'BAL (bronchoalveolar lavage)': 'organ_bal',
  'Synovial fluid': 'organ_synovialFluid',
  'Cyst fluid': 'organ_cystFluid',
  'Other': 'organ_other',
  'GYN Cytology (Pap smears)': 'organ_gynCytoSite',
  'Urine Cytology': 'organ_urineCytoSite',
  'CSF (Cerebrospinal fluid)': 'organ_csfSite',
};

export const SPECIMEN_TYPE_KEY_MAP: Record<string, keyof typeof en> = {
  'Biopsy': 'specimenType_biopsy',
  'Excision': 'specimenType_excision',
  'Resection': 'specimenType_resection',
  'Cytology': 'specimenType_cytology',
  'Core needle biopsy': 'specimenType_coreNeedleBiopsy',
  'Fine needle aspiration': 'specimenType_fineNeedleAspiration',
  'Curettage': 'specimenType_curettage',
  'Polypectomy': 'specimenType_polypectomy',
  'Amputation': 'specimenType_amputation',
  'Bone marrow biopsy': 'specimenType_boneMarrowBiopsy',
};

export const SLIDE_TYPE_KEY_MAP: Record<string, keyof typeof en> = {
  'H&E': 'slideType_he',
  'Unstained': 'slideType_unstained',
  'IHC': 'slideType_ihc',
  'Special stain': 'slideType_specialStain',
  'Other': 'slideType_other',
};

export const CASE_TYPE_KEY_MAP: Record<string, keyof typeof en> = {
  'Surgical Pathology': 'oe_surgicalPathology',
  'Cytology': 'oe_cytology',
};

export const SEX_KEY_MAP: Record<string, keyof typeof en> = {
  'Male': 'oe_sexMale',
  'Female': 'oe_sexFemale',
  'Other': 'oe_sexOther',
  'Unknown': 'oe_sexUnknown',
};

export const ROLE_KEY_MAP: Record<string, keyof typeof en> = {
  'Pathologist': 'role_pathologist',
  'Technologist': 'role_technologist',
};

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------

type TranslationKey = keyof typeof en;
type Translations = Readonly<Record<TranslationKey, string>>;

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  direction: 'ltr' | 'rtl';
  languageOptions: readonly LanguageOption[];
  t: (key: keyof Translations) => string;
  tSite: (englishName: string) => string;
  tOrgan: (englishName: string) => string;
  tSpecimenType: (englishName: string) => string;
  tSlideType: (englishName: string) => string;
  tCaseType: (englishName: string) => string;
  tSex: (englishName: string) => string;
  tRole: (englishName: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

const DICTS: Partial<Record<Lang, Translations>> = { en, sw, fr, ar, ur };

function isSupportedLanguage(value: string | null): value is Lang {
  return value !== null && APP_LANGUAGE_CODES.includes(value as Lang);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const stored = (typeof localStorage !== 'undefined' ? localStorage.getItem('ap_lis_lang') : null) as Lang | null;
  const [lang, setLangState] = useState<Lang>(isSupportedLanguage(stored) ? stored : 'en');

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem('ap_lis_lang', l);
  }, []);

  const dict = DICTS[lang] ?? en;
  const direction = LANGUAGE_OPTIONS_BY_CODE[lang]?.direction ?? 'ltr';

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = direction;
  }, [direction, lang]);

  const t = (key: keyof Translations) => dict[key] as string;
  const tSite = (name: string) => {
    const key = SITE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tOrgan = (name: string) => {
    const key = ORGAN_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tSpecimenType = (name: string) => {
    const key = SPECIMEN_TYPE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tSlideType = (name: string) => {
    const key = SLIDE_TYPE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tCaseType = (name: string) => {
    const key = CASE_TYPE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tSex = (name: string) => {
    const key = SEX_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };
  const tRole = (name: string) => {
    const key = ROLE_KEY_MAP[name];
    return key ? (dict[key] as string) : name;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, direction, languageOptions: LANGUAGE_OPTIONS, t, tSite, tOrgan, tSpecimenType, tSlideType, tCaseType, tSex, tRole }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
