/**
 * Deployment resource profile — container memory and CPU, at idle and under load,
 * measured on the machine that runs it.
 *
 *   pnpm metrics:deployment
 *
 *   --keep-up            leave the stack running afterwards (default: tear down)
 *   --skip-load          idle profile only; skips the benchmark
 *   --skip-replicated    skip the replicated-topology idle profile
 *   --samples=N          samples per window        (default 12)
 *   --interval=MS        gap between samples       (default 5000)
 *   --settle=SECONDS     quiet period before the idle window (default 30)
 *
 * Writes docs/verification/deployment-profile-<stamp>.{md,json}, and pairs with
 * the benchmark-<stamp>.{md,json} written by the run it drives.
 *
 * Why this exists: the manuscript's only resource evidence was "131.75 MB idle,
 * CPU < 0.5%", and neither figure had any provenance in this repository — no
 * command, no host, no timestamp, no commit. Nothing here measured container
 * consumption at all: describeHost() in benchmark.ts records host *capacity*
 * (os.totalmem, os.cpus), never what the stack actually uses. Measuring a
 * container footprint requires the app to run in containers, which neither CI nor
 * the documented local recipe does — both run backend and frontend as host
 * processes. Hence a Docker-based profiler.
 *
 * Why this is deliberately NOT a GitHub workflow, unlike verification.yml: the
 * measurement characterises a host. A shared CI runner would produce a footprint
 * with no deployment meaning, which is worse than no number at all. This is the
 * one metric in the repository that must be generated by a person on a named
 * machine.
 */
import { execFileSync, spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputDir = path.join(repoRoot, 'docs', 'verification');

// ─── Options ────────────────────────────────────────────────────────────────

function flag(name: string): boolean {
  return process.argv.includes(`--${name}`);
}

function option(name: string, fallback: number): number {
  const match = process.argv.find((argument) => argument.startsWith(`--${name}=`));
  if (!match) return fallback;
  const value = Number(match.split('=')[1]);
  return Number.isFinite(value) && value > 0 ? value : fallback;
}

const keepUp = flag('keep-up');
const skipLoad = flag('skip-load');
const skipReplicated = flag('skip-replicated');
const SAMPLES = option('samples', 12);
const INTERVAL_MS = option('interval', 5000);
const SETTLE_SECONDS = option('settle', 30);

// ─── Topologies ─────────────────────────────────────────────────────────────

const REPLICATED_ENV_FILE = path.join(repoRoot, '.env.profile-replicated');

interface Topology {
  key: 'single-node' | 'replicated';
  label: string;
  project: string;
  files: string[];
  envFile?: string;
  /** Host origin for the backend, used for readiness and for the benchmark. */
  backendUrl: string;
  /** Host DSN for the database, used by the benchmark's Prisma client. */
  databaseUrl?: string;
}

const SINGLE_NODE: Topology = {
  key: 'single-node',
  label: 'Single-node (docker-compose.yml)',
  project: 'lis-profile',
  files: ['docker-compose.yml', 'docker-compose.profile.yml'],
  backendUrl: 'http://localhost:3101',
  databaseUrl: 'postgresql://lis_user:lis_password@localhost:55432/lis_db',
};

const REPLICATED: Topology = {
  key: 'replicated',
  label: 'Replicated primary + hot standby (docker-compose.prod.yml)',
  project: 'lis-profile-repl',
  files: ['docker-compose.prod.yml', 'docker-compose.profile-replicated.yml'],
  envFile: REPLICATED_ENV_FILE,
  backendUrl: 'http://localhost:3102',
};

function composeArgs(topology: Topology, ...rest: string[]): string[] {
  const args = ['compose', '-p', topology.project];
  if (topology.envFile) args.push('--env-file', topology.envFile);
  for (const file of topology.files) args.push('-f', file);
  return [...args, ...rest];
}

function docker(args: string[], options: { quiet?: boolean } = {}): string {
  return execFileSync('docker', args, {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: options.quiet ? ['ignore', 'pipe', 'pipe'] : ['ignore', 'pipe', 'inherit'],
    maxBuffer: 32 * 1024 * 1024,
  });
}

// ─── Environment capture ────────────────────────────────────────────────────

/**
 * Everything a reader needs to interpret the numbers below, collected rather than
 * typed. The Docker/WSL configuration is what decides whether a footprint is
 * meaningful — a stack squeezed against a low WSL2 memory ceiling behaves
 * differently from one with headroom — and it is exactly the sort of detail that
 * gets lost when figures are transcribed by hand.
 */
function describeEnvironment(): Record<string, string> {
  const environment: Record<string, string> = {};

  let commit = 'unknown (not a git checkout)';
  try {
    commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: repoRoot, encoding: 'utf8' }).trim();
  } catch {
    // Reported as unknown rather than omitted.
  }
  environment.commit = commit;
  environment.node = process.version;
  environment.platform = `${os.type()} ${os.release()} (${os.arch()})`;
  environment.hostCpu = os.cpus()[0]?.model ?? 'unknown';
  environment.hostLogicalCores = String(os.cpus().length);
  environment.hostTotalMemoryGiB = (os.totalmem() / 1024 ** 3).toFixed(2);

  try {
    environment.dockerVersion = docker(
      ['version', '--format', '{{.Server.Version}}'],
      { quiet: true }
    ).trim();
  } catch {
    environment.dockerVersion = 'unknown';
  }

  // These five fields together pin the container runtime: OperatingSystem
  // distinguishes Docker Desktop from a plain engine, Kernel reveals whether the
  // WSL2 backend is in use, and MemTotal/NCPU are the ceiling the containers
  // actually see — which on Windows comes from .wslconfig, not from Docker.
  for (const [key, template] of [
    ['dockerOperatingSystem', '{{.OperatingSystem}}'],
    ['dockerKernel', '{{.KernelVersion}}'],
    ['dockerCgroupVersion', '{{.CgroupVersion}}'],
    ['dockerNCPU', '{{.NCPU}}'],
    ['dockerMemTotalGiB', '{{.MemTotal}}'],
  ] as const) {
    try {
      const raw = docker(['info', '--format', template], { quiet: true }).trim();
      environment[key] =
        key === 'dockerMemTotalGiB' ? (Number(raw) / 1024 ** 3).toFixed(2) : raw;
    } catch {
      environment[key] = 'unknown';
    }
  }

  environment.dockerBackend = /WSL2/i.test(environment.dockerKernel ?? '')
    ? 'Docker Desktop, WSL2 backend'
    : 'not WSL2 (native engine or Hyper-V backend)';

  // The settle period belongs in the record because it changes the answer: the
  // same stack on this host measured 157.69 MB after 5s and 126.32 MB after 25s,
  // because PostgreSQL is still working through the 300-case seed. An idle figure
  // without its settle time is not reproducible.
  environment.settleSeconds = String(SETTLE_SECONDS);
  environment.idleSampling = `polled, ${SAMPLES} samples at ${INTERVAL_MS} ms`;
  environment.loadSampling = 'streamed from one `docker stats` process, ~1 reading/s, for the benchmark’s duration';

  // On Windows the WSL2 VM's memory and CPU ceiling comes from .wslconfig, not
  // from Docker Desktop's own settings. Its absence is a finding, not a gap: WSL2
  // then defaults to roughly 50% of host RAM and all logical processors.
  const wslConfigPath = path.join(os.homedir(), '.wslconfig');
  if (existsSync(wslConfigPath)) {
    environment.wslConfig = readFileSync(wslConfigPath, 'utf8').trim().replace(/\s*\n\s*/g, '; ');
  } else {
    environment.wslConfig =
      'absent — WSL2 defaults apply (memory ≈ 50% of host RAM, all logical processors)';
  }

  return environment;
}

// ─── docker stats sampling ──────────────────────────────────────────────────

interface StatSample {
  container: string;
  memoryBytes: number;
  cpuPercent: number;
}

interface Distribution {
  samples: number;
  min: number;
  p50: number;
  max: number;
}

interface ContainerProfile {
  container: string;
  memoryBytes: Distribution;
  cpuPercent: Distribution;
}

interface ResourceWindow {
  label: string;
  topology: string;
  samples: number;
  intervalMs: number;
  containers: ContainerProfile[];
  totalMemoryBytes: Distribution;
  totalCpuPercent: Distribution;
}

/**
 * Parses the human-readable sizes docker stats emits ("49.52MiB", "1.2GB").
 * Both binary and decimal suffixes appear depending on platform and version.
 */
function parseBytes(text: string): number {
  const match = /^([\d.]+)\s*([A-Za-z]*)$/.exec(text.trim());
  if (!match) return 0;
  const value = Number(match[1]);
  const units: Record<string, number> = {
    b: 1,
    kb: 1000,
    mb: 1000 ** 2,
    gb: 1000 ** 3,
    tb: 1000 ** 4,
    kib: 1024,
    mib: 1024 ** 2,
    gib: 1024 ** 3,
    tib: 1024 ** 4,
  };
  return Number.isFinite(value) ? value * (units[match[2].toLowerCase()] ?? 1) : 0;
}

/**
 * min/p50/max rather than a mean, and never a single reading.
 *
 * Duplicated in spirit from summarize() in scripts/benchmark.ts rather than
 * shared, following the convention used by the other standalone scripts: they run
 * independently and are kept in step by hand. A distribution also happens to be
 * the honest replacement for the manuscript's "CPU utilization < 0.5%", which was
 * one idle sample presented as a property of the system.
 */
function distribution(values: number[]): Distribution {
  if (values.length === 0) return { samples: 0, min: 0, p50: 0, max: 0 };
  const sorted = [...values].sort((left, right) => left - right);
  const round = (value: number): number => Math.round(value * 100) / 100;
  return {
    samples: sorted.length,
    min: round(sorted[0]),
    p50: round(sorted[Math.min(sorted.length - 1, Math.floor(0.5 * sorted.length))]),
    max: round(sorted[sorted.length - 1]),
  };
}

function runningContainers(topology: Topology): string[] {
  const raw = docker(composeArgs(topology, 'ps', '--format', '{{.Name}}'), { quiet: true });
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

function sampleOnce(containers: string[]): StatSample[] {
  if (containers.length === 0) return [];
  // Explicit container names rather than an unfiltered `docker stats`, so a
  // developer's own stack running alongside this one is never counted.
  const raw = docker(['stats', '--no-stream', '--format', '{{json .}}', ...containers], {
    quiet: true,
  });

  const samples: StatSample[] = [];
  for (const line of raw.split(/\r?\n/)) {
    if (!line.trim()) continue;
    try {
      const row = JSON.parse(line) as { Name?: string; MemUsage?: string; CPUPerc?: string };
      if (!row.Name) continue;
      samples.push({
        container: row.Name,
        memoryBytes: parseBytes((row.MemUsage ?? '0B').split('/')[0]),
        cpuPercent: Number((row.CPUPerc ?? '0%').replace('%', '')) || 0,
      });
    } catch {
      // A malformed line is skipped; the window still reports the rest.
    }
  }
  return samples;
}

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * Samples continuously from a single streaming `docker stats` process until `stop`
 * resolves, then returns the window.
 *
 * The polling path below calls `docker stats --no-stream` once per sample, and
 * each of those costs two to four seconds because Docker itself needs two reads to
 * compute a CPU delta. That is fine for a stationary idle stack, but it makes the
 * loaded window latency-bound rather than interval-bound: two runs of the same
 * benchmark sampled at that cadence reported peak stack memory of 574 MB and
 * 391 MB, because the sampler stepped over the phase where headless Chromium is
 * resident. A peak that moves by 45% between runs is not a measurement — the same
 * objection this script's storage metric was rewritten to answer.
 *
 * Streaming keeps one process alive and takes a reading roughly every second, so
 * the loaded window actually resolves the workload's phases.
 */
async function streamWindow(
  topology: Topology,
  label: string,
  stop: Promise<void>
): Promise<ResourceWindow> {
  const containers = runningContainers(topology);
  if (containers.length === 0) {
    return {
      label,
      topology: topology.label,
      samples: 0,
      intervalMs: 0,
      containers: [],
      totalMemoryBytes: distribution([]),
      totalCpuPercent: distribution([]),
    };
  }

  const child = spawn('docker', ['stats', '--format', '{{json .}}', ...containers], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  // Kept rather than discarded: silencing this stream is what let a parse bug
  // present itself as a window of "0.00 MB" instead of an error.
  let stderr = '';
  child.stderr.on('data', (chunk: Buffer) => {
    stderr += chunk.toString('utf8');
  });

  const collected: StatSample[] = [];
  const totalsMemory: number[] = [];
  const totalsCpu: number[] = [];

  // Streaming mode redraws the terminal, so each refresh begins with a cursor-home
  // escape (ESC[H) on its first container row. That marker is the refresh boundary
  // used to group readings into per-refresh stack totals.
  let group: StatSample[] = [];
  const flush = (): void => {
    if (group.length === 0) return;
    collected.push(...group);
    totalsMemory.push(group.reduce((sum, sample) => sum + sample.memoryBytes, 0));
    totalsCpu.push(group.reduce((sum, sample) => sum + sample.cpuPercent, 0));
    group = [];
  };

  let buffer = '';
  child.stdout.on('data', (chunk: Buffer) => {
    buffer += chunk.toString('utf8');
    const lines = buffer.split(/\r?\n/);
    buffer = lines.pop() ?? '';
    for (const line of lines) {
      // Rows arrive wrapped in cursor control: ESC[H{…json…}ESC[K. Slicing from the
      // first brace to the *last* one is what makes them parseable — taking the
      // rest of the line leaves the trailing escape inside the JSON.
      const start = line.indexOf('{');
      const end = line.lastIndexOf('}');
      if (start === -1 || end < start) continue;
      const newRefresh = line.slice(0, start).includes('[H');
      try {
        const row = JSON.parse(line.slice(start, end + 1)) as {
          Name?: string;
          MemUsage?: string;
          CPUPerc?: string;
        };
        if (!row.Name || !containers.includes(row.Name)) continue;
        if (newRefresh || group.some((sample) => sample.container === row.Name)) flush();
        group.push({
          container: row.Name,
          memoryBytes: parseBytes((row.MemUsage ?? '0B').split('/')[0]),
          cpuPercent: Number((row.CPUPerc ?? '0%').replace('%', '')) || 0,
        });
      } catch {
        // Partial or decorated line; the window still reports the rest.
      }
    }
  });

  await stop;
  flush();
  child.kill();

  if (totalsMemory.length === 0) {
    console.error(
      `[warn] streamed window "${label}" collected no samples. ` +
        `docker stats stderr: ${stderr.trim() || '(empty)'}`
    );
  }

  const byContainer = new Map<string, StatSample[]>();
  for (const sample of collected) {
    const list = byContainer.get(sample.container) ?? [];
    list.push(sample);
    byContainer.set(sample.container, list);
  }

  return {
    label,
    topology: topology.label,
    samples: totalsMemory.length,
    intervalMs: 1000,
    containers: [...byContainer.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([container, samples]) => ({
        container,
        memoryBytes: distribution(samples.map((sample) => sample.memoryBytes)),
        cpuPercent: distribution(samples.map((sample) => sample.cpuPercent)),
      })),
    totalMemoryBytes: distribution(totalsMemory),
    totalCpuPercent: distribution(totalsCpu),
  };
}

/**
 * Polls a stationary stack: one `docker stats --no-stream` call per sample. Used
 * for idle windows, where a slow cadence costs nothing because nothing is moving.
 * Loaded windows use streamWindow() instead — see the note there.
 */
async function sampleWindow(topology: Topology, label: string): Promise<ResourceWindow> {
  const containers = runningContainers(topology);
  const target = SAMPLES;
  const intervalMs = INTERVAL_MS;
  const collected: StatSample[] = [];
  const totalsMemory: number[] = [];
  const totalsCpu: number[] = [];

  for (let index = 0; index < target; index += 1) {
    const batch = sampleOnce(containers);
    if (batch.length > 0) {
      collected.push(...batch);
      totalsMemory.push(batch.reduce((sum, sample) => sum + sample.memoryBytes, 0));
      totalsCpu.push(batch.reduce((sum, sample) => sum + sample.cpuPercent, 0));
    }
    if (index < target - 1) await sleep(intervalMs);
  }

  const byContainer = new Map<string, StatSample[]>();
  for (const sample of collected) {
    const list = byContainer.get(sample.container) ?? [];
    list.push(sample);
    byContainer.set(sample.container, list);
  }

  return {
    label,
    topology: topology.label,
    samples: totalsMemory.length,
    intervalMs,
    containers: [...byContainer.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([container, samples]) => ({
        container,
        memoryBytes: distribution(samples.map((sample) => sample.memoryBytes)),
        cpuPercent: distribution(samples.map((sample) => sample.cpuPercent)),
      })),
    totalMemoryBytes: distribution(totalsMemory),
    totalCpuPercent: distribution(totalsCpu),
  };
}

// ─── Stack lifecycle ────────────────────────────────────────────────────────

async function waitForBackend(url: string, timeoutSeconds: number): Promise<void> {
  const deadline = Date.now() + timeoutSeconds * 1000;
  while (Date.now() < deadline) {
    const response = await fetch(`${url}/health`).catch(() => null);
    if (response?.ok) return;
    await sleep(3000);
  }
  throw new Error(`Backend at ${url}/health did not become ready within ${timeoutSeconds}s.`);
}

function bringUp(topology: Topology): void {
  console.log(`\n[${topology.key}] docker compose up (build + wait)…`);
  // down -v first so the corpus is the deterministic 300-case seed rather than
  // whatever a previous run left behind. Safe because the project name isolates
  // these volumes from the developer's default stack.
  docker(composeArgs(topology, 'down', '-v', '--remove-orphans'));
  docker(composeArgs(topology, 'up', '-d', '--build', '--wait', '--wait-timeout', '600'));
}

function tearDown(topology: Topology): void {
  try {
    docker(composeArgs(topology, 'down', '-v', '--remove-orphans'));
  } catch (error) {
    console.error(
      `[${topology.key}] teardown failed: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/**
 * The replicated stack interpolates ${VAR} from an env file at compose-parse time
 * and its backend reads one at runtime, so both need to exist before it will come
 * up. Credentials are generated per run and the file is removed afterwards —
 * nothing here is a real secret, and it never touches .env.production.
 */
function writeReplicatedEnvFile(): void {
  const secret = (): string => randomBytes(24).toString('hex');
  const dbPassword = secret();
  const lines = [
    '# Generated by `pnpm metrics:deployment` — throwaway credentials, deleted after the run.',
    'NODE_ENV=production',
    'COOKIE_SECURE=false',
    'PORT=3001',
    'CORS_ORIGIN=http://localhost:5274',
    'STORAGE_PATH=./storage',
    `SESSION_SECRET=${secret()}`,
    'POSTGRES_USER=lis_user',
    `POSTGRES_PASSWORD=${dbPassword}`,
    'POSTGRES_DB=lis_db',
    `REPLICATION_PASSWORD=${secret()}`,
    `DATABASE_URL=postgresql://lis_user:${dbPassword}@postgres_primary:5432/lis_db`,
    `DATABASE_URL_REPLICA=postgresql://lis_user:${dbPassword}@postgres_standby:5432/lis_db`,
    // Empty prefix keeps WAL archiving local (archive-wrapper.sh falls back to the
    // wal_archive volume), so no GCS credentials are needed.
    'WALG_GCS_PREFIX=',
    'WALG_COMPRESSION_METHOD=lz4',
    'GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-sa.json',
    '',
  ];
  writeFileSync(REPLICATED_ENV_FILE, lines.join('\n'), 'utf8');

  // docker-compose.prod.yml bind-mounts ./secrets read-only into all three
  // Postgres-image services. With WALG_GCS_PREFIX empty the file is never read,
  // but the mount source still has to exist.
  const secretsDir = path.join(repoRoot, 'secrets');
  mkdirSync(secretsDir, { recursive: true });
  const placeholder = path.join(secretsDir, 'gcp-sa.json');
  if (!existsSync(placeholder)) {
    writeFileSync(placeholder, '{}\n', 'utf8');
  }
}

// ─── Benchmark under sampling ───────────────────────────────────────────────

interface BenchmarkOutcome {
  ran: boolean;
  exitCode: number | null;
  storage?: Record<string, unknown>;
  note?: string;
}

/**
 * Runs `pnpm bench` against the profile stack while sampling the containers.
 *
 * spawn rather than the spawnSync used elsewhere in scripts/: the whole point is
 * to sample concurrently with the workload, which a synchronous call forecloses.
 */
async function runBenchmarkUnderLoad(
  topology: Topology,
  stamp: string
): Promise<{ outcome: BenchmarkOutcome; window: ResourceWindow | null }> {
  console.log(`\n[${topology.key}] running pnpm bench under sampling…`);

  let exitCode: number | null = null;

  const child = spawn('pnpm', ['bench'], {
    cwd: repoRoot,
    shell: true,
    stdio: ['ignore', 'inherit', 'inherit'],
    env: {
      ...process.env,
      BENCH_BASE_URL: topology.backendUrl,
      // Explicit, because Prisma loads the repo-root .env on import and would
      // otherwise point the storage measurement at the developer's database.
      DATABASE_URL: topology.databaseUrl,
      PROFILE_STAMP: stamp,
    },
  });

  const completion = new Promise<void>((resolve) => {
    child.on('close', (code) => {
      exitCode = code;
      resolve();
    });
  });

  // Streamed rather than polled, so the window covers exactly the loaded period at
  // roughly one reading per second.
  const window = await streamWindow(topology, 'Under load (pnpm bench)', completion);

  const outcome: BenchmarkOutcome = { ran: true, exitCode };
  const jsonPath = path.join(outputDir, `benchmark-${stamp}.json`);
  if (existsSync(jsonPath)) {
    try {
      const parsed = JSON.parse(readFileSync(jsonPath, 'utf8')) as { storage?: Record<string, unknown> };
      outcome.storage = parsed.storage;
    } catch {
      outcome.note = 'Benchmark JSON could not be parsed for storage figures.';
    }
  } else {
    outcome.note = `Benchmark wrote no JSON (exit code ${exitCode ?? 'unknown'}).`;
  }

  return { outcome, window };
}

// ─── Rendering ──────────────────────────────────────────────────────────────

const mib = (bytes: number): string => (bytes / 1024 ** 2).toFixed(2);

function renderWindow(window: ResourceWindow): string[] {
  if (window.samples === 0) {
    return [`_No samples collected for **${window.label}**._`, ''];
  }
  return [
    `### ${window.label}`,
    '',
    `${window.samples} samples at ${window.intervalMs} ms — ${window.topology}.`,
    '',
    '| Container | Memory p50 | Memory max | CPU p50 | CPU max |',
    '| --- | ---: | ---: | ---: | ---: |',
    ...window.containers.map(
      (container) =>
        `| \`${container.container}\` | ${mib(container.memoryBytes.p50)} MB | ${mib(
          container.memoryBytes.max
        )} MB | ${container.cpuPercent.p50}% | ${container.cpuPercent.max}% |`
    ),
    `| **Stack total** | **${mib(window.totalMemoryBytes.p50)} MB** | **${mib(
      window.totalMemoryBytes.max
    )} MB** | **${window.totalCpuPercent.p50}%** | **${window.totalCpuPercent.max}%** |`,
    '',
  ];
}

function renderMarkdown(
  environment: Record<string, string>,
  windows: ResourceWindow[],
  benchmark: BenchmarkOutcome,
  stamp: string,
  generatedAt: string
): string {
  const lines = [
    '# Deployment resource profile',
    '',
    'Generated by `pnpm metrics:deployment` — do not edit by hand.',
    '',
    `- Commit: \`${environment.commit}\``,
    `- Generated: ${generatedAt}`,
    '- Measured on the host below, not in CI. These figures characterise a machine,',
    '  so a shared runner would produce a number with no deployment meaning.',
    '',
    '## Environment',
    '',
    '| Property | Value |',
    '| --- | --- |',
    ...Object.entries(environment).map(([key, value]) => `| ${key} | ${value} |`),
    '',
    '## Resource windows',
    '',
    'Memory and CPU are per-container readings from `docker stats`, reported as a',
    'distribution across repeated samples rather than as a single reading. A lone',
    '`docker stats --no-stream` CPU value is unreliable, and a one-off idle sample is',
    'what produced the unsupportable "CPU utilization < 0.5%" figure this replaces.',
    '',
    '**These totals are not the host cost.** `docker stats` reports each container’s',
    'cgroup working set and excludes the overhead of the virtual machine the engine',
    'runs in — on Docker Desktop with the WSL2 backend, the VM itself. Treat the',
    'stack total as a lower bound on what a host must provide.',
    '',
  ];

  for (const window of windows) lines.push(...renderWindow(window));

  const storage = benchmark.storage as
    | { cases?: number; bytesPerCase?: number; caseScalingBytes?: number; referenceBytes?: number }
    | undefined;

  lines.push('## Storage', '');
  if (storage?.cases) {
    lines.push(
      `Measured by the paired benchmark run on the pristine seeded corpus, before it`,
      `inserted cases of its own. Full per-table breakdown in \`benchmark-${stamp}.md\`.`,
      '',
      '| Measure | Value |',
      '| --- | ---: |',
      `| Cases in the corpus | ${storage.cases} |`,
      `| Case-scaling tables, total | ${mib(storage.caseScalingBytes ?? 0)} MB |`,
      `| Reference and configuration tables, total | ${mib(storage.referenceBytes ?? 0)} MB |`,
      `| **Storage per case** | **${((storage.bytesPerCase ?? 0) / 1024).toFixed(1)} KB** |`,
      ''
    );
  } else {
    lines.push(
      benchmark.ran
        ? `_Not available: ${benchmark.note ?? 'the benchmark produced no storage figures.'}_`
        : '_Skipped (`--skip-load`)._',
      ''
    );
  }

  lines.push(
    '## Reproducing this',
    '',
    '```bash',
    'pnpm metrics:deployment',
    '```',
    '',
    'The profile stack runs under its own Compose project name with its own volumes and',
    'remapped ports, so it neither reads nor destroys a developer’s database and can run',
    'while the default stack is up. It starts from `down -v`, so the corpus is always the',
    'deterministic 300-case seed.',
    ''
  );

  if (benchmark.ran && benchmark.exitCode !== 0) {
    lines.push(
      `> The benchmark exited with code ${benchmark.exitCode}. Its own report records which`,
      '> scenarios failed; the resource windows above are still valid for the period sampled.',
      ''
    );
  }

  return lines.join('\n');
}

// ─── Entry point ────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  try {
    docker(['version', '--format', '{{.Server.Version}}'], { quiet: true });
  } catch {
    throw new Error(
      'Docker is not available. Start Docker Desktop (or the engine) and re-run.'
    );
  }

  const generatedAt = new Date().toISOString();
  const stamp = generatedAt.replace(/[:.]/g, '-');
  const environment = describeEnvironment();
  const windows: ResourceWindow[] = [];
  let benchmark: BenchmarkOutcome = { ran: false, exitCode: null };

  console.log(
    `Docker ${environment.dockerVersion} — ${environment.dockerBackend}\n` +
      `Engine sees ${environment.dockerNCPU} CPUs and ${environment.dockerMemTotalGiB} GiB\n` +
      `.wslconfig: ${environment.wslConfig}`
  );

  const started: Topology[] = [];
  try {
    bringUp(SINGLE_NODE);
    started.push(SINGLE_NODE);
    await waitForBackend(SINGLE_NODE.backendUrl, 300);

    console.log(`\n[single-node] settling ${SETTLE_SECONDS}s before the idle window…`);
    await sleep(SETTLE_SECONDS * 1000);
    windows.push(await sampleWindow(SINGLE_NODE, 'Idle, single-node'));

    if (!skipLoad) {
      const result = await runBenchmarkUnderLoad(SINGLE_NODE, stamp);
      benchmark = result.outcome;
      if (result.window) windows.push(result.window);
    }

    if (!skipReplicated) {
      // Torn down before the replicated stack starts: two stacks running at once
      // would contend for CPU and memory and corrupt both idle windows.
      if (!keepUp) {
        tearDown(SINGLE_NODE);
        started.pop();
      }
      try {
        writeReplicatedEnvFile();
        bringUp(REPLICATED);
        started.push(REPLICATED);
        await waitForBackend(REPLICATED.backendUrl, 420);
        console.log(`\n[replicated] settling ${SETTLE_SECONDS}s before the idle window…`);
        await sleep(SETTLE_SECONDS * 1000);
        windows.push(await sampleWindow(REPLICATED, 'Idle, replicated (primary + hot standby)'));
      } catch (error) {
        console.error(
          `\n[replicated] skipped: ${error instanceof Error ? error.message : String(error)}`
        );
        environment.replicatedProfile = `skipped — ${
          error instanceof Error ? error.message : String(error)
        }`;
      }
    }
  } finally {
    if (!keepUp) {
      for (const topology of started) tearDown(topology);
      if (existsSync(REPLICATED_ENV_FILE)) rmSync(REPLICATED_ENV_FILE, { force: true });
    } else {
      console.log('\n--keep-up: stacks left running. Tear down with:');
      for (const topology of started) {
        console.log(`  docker ${composeArgs(topology, 'down', '-v').join(' ')}`);
      }
    }
  }

  mkdirSync(outputDir, { recursive: true });
  const jsonPath = path.join(outputDir, `deployment-profile-${stamp}.json`);
  const markdownPath = path.join(outputDir, `deployment-profile-${stamp}.md`);
  writeFileSync(
    jsonPath,
    `${JSON.stringify({ ...environment, generatedAt, windows, benchmark }, null, 2)}\n`,
    'utf8'
  );
  writeFileSync(
    markdownPath,
    renderMarkdown(environment, windows, benchmark, stamp, generatedAt),
    'utf8'
  );

  for (const window of windows) {
    console.log(
      `\n${window.label}: stack total memory p50 ${mib(window.totalMemoryBytes.p50)} MB, ` +
        `max ${mib(window.totalMemoryBytes.max)} MB; CPU p50 ${window.totalCpuPercent.p50}%, ` +
        `max ${window.totalCpuPercent.max}% (${window.samples} samples)`
    );
  }
  console.log(`\nWrote ${path.relative(repoRoot, markdownPath)} and ${path.relative(repoRoot, jsonPath)}`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
